### ISSUE TITLE
error: Invalid path

### ISSUE THREAD

**Issue by dutu** [bitfinexcom/bitfinex-api-node#10]
invalid character is used and error received in windows

c:\@personal\Projects>git clone https://github.com/bitfinexcom/bitfinex-api-node.git
Cloning into 'bitfinex-api-node'...
remote: Counting objects: 1844, done.
remote: Compressing objects: 100% (3/3), done.
Receiving objects:  99% (1826/1844), 1.54 MiB | 332.00 KiB/s   8R41
Receiving objects: 100% (1844/1844), 1.60 MiB | 332.00 KiB/s, done.
Resolving deltas: 100% (1077/1077), done.
Checking connectivity... done.
error: Invalid path 'source/images/coveragelcov-report/prettify.css'
error: Invalid path 'source/images/coveragelcov-report/prettify.js'
error: Invalid path 'source/images/coveragelcov-report/sort-arrow-sprite.png'
error: Invalid path 'source/images/coveragelcov-report/sorter.js'
error: Invalid path 'source/images/coveragelcov.info'

c:\@personal\Projects>

**Comment by dutu** [comment]
npm update (in windows) also fails to install the module

**Comment by jared-jacobson** [comment]
C:\Development\testproj\npm install bitfinex-api-node --save
extract:json-schema -> ge - |###############################################-----------------|

Just stops at this point in Windows 10 and installation hangs...

Tried deleting the local package folder and retrying.
Tried running npm cache clean.
Tried different versions of node

**Comment by joshuarossi** [comment]
can you try this again?

**Comment by dutu** [comment]
it works, thanks (problematic files are not in the package anymore)
