### ISSUE TITLE
Could someone provide usage examples for REST?

### ISSUE THREAD

**Issue by cameronlockey** [bitfinexcom/bitfinex-api-node#102]
Thanks for building this. Could the README be expanded to demonstrate usage of the REST endpoints?

I realize it may well be basic node conventions that I am missing, but I am trying to inspect the data response for an authenticated REST endpoint (movements), and can't figure out how to see whether I got the data response I expect.

```
const rest = new BFX(API_KEY, API_SECRET, opts).rest
var yesterday = moment().subtract(1, 'days').unix();
var today = moment().startOf('day').unix();

movement_opts = {
  "since": yesterday,
  "until": today
};

response = rest.movements('BTCUSD', movement_opts, function(error, data){
  console.log(error);
  console.log(data);
});
```
When I run this, I get:

```
vagrant@localhost:/vagrant/bitfinex$ node bitfinex-test.js
null
[]
```

**Comment by Tetradeca** [comment]
Can you double check that the time on your vagrant box is up-to-date?

**Comment by cameronlockey** [comment]
Just checked, and got `Thu Aug 24 21:43:34 EDT 2017`

**Comment by cameronlockey** [comment]
Okay. I checked a different endpoint, and was able to retrieve data using much the same method as above. So, I believe my empty array response from `movements` is just because there is no data in my account for the timeframe provided.
