### ISSUE TITLE
option to don't use WS or REST

### ISSUE THREAD

**Issue by hems** [bitfinexcom/bitfinex-api-node#104]
If you need multiple instances for REST you won't need a new WS every time you creste and instance sonideally we would be able to pass an option in order to don't open an WS connection

**Comment by robertkowalski** [comment]
hi @hems,

good point. we are already working on a permanent solution.

for now you can just pass: `autoOpen: false` as option:

```js
const bfx = new BFX('apikey', 'apisecret', { version: 2, autoOpen: false })
```

**Comment by robertkowalski** [comment]
related: https://github.com/bitfinexcom/bitfinex-api-node/issues/41

**Comment by hems** [comment]
tks!
