### ISSUE TITLE
Nonce behavior

### ISSUE THREAD

**Issue by Tetradeca** [bitfinexcom/bitfinex-api-node#108]
As stated in the docs, the nonce should be strictly increasing. Unfortunately sometimes it happens that you need to query two different API's at the same timestamp, or the same with different parameters.

I tried providing a high resolution time expressed in seconds and nanoseconds (`10206113444118`), but it appears the API does not really handles that correctly, and tells me that my nonce is too small for every subsequent call I make.

Is this something you would consider? Having a global app debouncing to get around this behavior looks quite ugly to me.

**Comment by robertkowalski** [comment]
Good catch!

I think thats a missing feature of the ws2 client. The rest client supports it already: https://github.com/bitfinexcom/bitfinex-api-node/blob/7312e92a6e83061db7d551fff38ef0d0aa80c6a3/rest2.js#L14

It takes the current timestamp and lets every request just increase the number unix timestamp.

I think its worth to add that to the ws implementations as well!

**Comment by Tetradeca** [comment]
Hum I was not talking about ws, but yes that's also a good point.
What I did was to replace the default `nonceGenerator` by:

```js
const [seconds, nano] = process.hrtime()
return seconds * 1E9 + nano * 1E3
```

Unfortunately it doesn't seem like the api supports numbers that big. Do you have any insights on that?

**Comment by ilyacherevkov** [comment]
Nanoseconds work for me, but I have ruby wrapper

**Comment by ilyacherevkov** [comment]
Btw, sometimes authentication fails even with nanoseconds, so I wrote re-auth logic on each fail

**Comment by Tetradeca** [comment]
What do you mean the authentification fails just if you provide a nano nonce? Your solution sounds pretty hacky 😄

**Comment by robertkowalski** [comment]
What speaks against taking the current timestamp and incrementing it by one for each request? Right now that means for multiple connections you need multiple API keys, but with that we buy us stability.
