### ISSUE TITLE
wrong invocation context (this) in _processUserEvent

### ISSUE THREAD

**Issue by dutu** [bitfinexcom/bitfinex-api-node#11]
`this.emit(event, ele)` in function `_processUserEvent` throws error due wrong invocation context (`this`) in `forEach`.
`forEach `should be called with second parameter `this`:

                data[0].forEach(function (ele) {
                    debug('Emitting \'%s\' %j', event, ele);
                    this.emit(event, ele);
                }, this);

**Comment by prdn** [comment]
Thanks for pointing out the issue. Any PR is really appreciated, otherwise we'll cover these issues asap

**Comment by joshuarossi** [comment]
should be fixed now
