### ISSUE TITLE
Websocket `subscribeCandles` -> receiving only `undefined {}`

### ISSUE THREAD

**Issue by metachris** [bitfinexcom/bitfinex-api-node#110]
I would like to receive candles via websockets by subscribing to the candles channel. But I always receive `undefined, {}` events:

    bws.on('open', () => {
        bws.subscribeCandles('OMGBTC', '1m')
    })

    bws.on('candles', (pair, candles) => {
        console.log('Candles:', pair, candles)
    })

The result is:

    bitfinex:ws Received message: [100547,[1504869180000,0.002798,0.0027994,0.0027994,0.002798,9.66895624]] +1s
    bitfinex:ws Emited message event +0ms
    bitfinex:ws Received data from a channel +0ms
    bitfinex:ws Message in 'candles' channel +0ms
    bitfinex:ws Emitting candles, undefined, {} +0ms
    Candles: undefined {}

Can you reproduce this?

**Comment by nedievas** [comment]
The same with 'tBTCUSD'.

```
WS open
New subscription: { channel: 'candles',
  chanId: 322773,
  symbol: undefined,
  key: 'trade:1m:tBTCUSD' }
Candles: undefined [ {},
...
```

**Comment by Tetradeca** [comment]
Are you sure you are using the latest version?

**Comment by nedievas** [comment]
v.1.2.0

**Comment by bda2206** [comment]
i fixed like this in ws2.js line 147.  

_processCandleEvent (msg, event) {
    if (msg[0] === 'hb') { // HeatBeart
      debug('Received HeatBeart in %s ticker channel', event.symbol)
      return
    }

    msg = msg[0]
    const res = this.transformer(msg, 'candles', event.symbol)
    debug('Emitting candles, %s, %j', event.symbol, res)
    this.emit('candles', event.key.toString().substr(10,7), res)
  }

**Comment by vinipuh5** [comment]
@metachris try to use versuin 1.2.1 and add 't' prefix for your currency pair, like this: 'tOMGBTC'.

**Comment by f3rno** [comment]
Not reproducible on the latest version
