### ISSUE TITLE
Websocket not open

### ISSUE THREAD

**Issue by androng** [bitfinexcom/bitfinex-api-node#112]
I am getting "websocket not open" errors every few hours. If someone has made code to reconnect, perhaps submit a pull request? Otherwise my program just crashes. Do I just use a try-catch and try to call "ws.open()" again?

![screen shot 2017-09-11 at 12 35 46](https://user-images.githubusercontent.com/605932/30293380-203c5152-96ee-11e7-81ae-ef509646ab5c.png)

**Comment by bda2206** [comment]
yes my websocket seems to have drifted off to reporting no candles overnight.

I'll try this
bws.on('error',bws = new BFX(API_KEY, API_SECRET, { version: 2 }).ws);

**Comment by bda2206** [comment]
the websocket slowly stops supplying candle data.  meh.

**Comment by androng** [comment]
Whatever this message means, the websocket stops giving heartbeat messages. I have to use `ws.close()` and then `ws.open()` to resume the candle feed.

**Comment by LRonHubs** [comment]
Do you need to resubscribe to everything after calling ws.open?

**Comment by androng** [comment]
Yes

**Comment by bda2206** [comment]
the candle data is available for some time after ws.open. gradually the
subscriptions appeared to expire. i’m using rest api now.

**Comment by LRonHubs** [comment]
Ok this is true for everything involving the websockets, including the orderbook. It is pretty hard to trade when the orderbook socket goes off and you have no idea, in fact the entire section of the API becomes useless.

**Comment by gandac** [comment]
Hey,
I reconnect on 'error' and 'close' events. I don't know if this is the correct mode to reconnect, but seems it works for me.

```
var bws = new BFX(API_KEY, API_SECRET, opts).ws;

bws.on('error', ()=>{bws = new BFX(API_KEY, API_SECRET, opts).ws} );

bws.on('close', ()=>{bws = new BFX(API_KEY, API_SECRET, opts).ws} );
```
