### ISSUE TITLE
docs!?

### ISSUE THREAD

**Issue by TestniTester** [bitfinexcom/bitfinex-api-node#114]
im new to node.js
this bitfinex-api-node
is not finished? or?
cant finds how to buy/sell...anything... except orderbook 
HELP!?

**Comment by robertkowalski** [comment]
Hi @TestniTester,

the project is finished, but we keep working on improving it. In the future we have to improve the docs a lot to make them nicer. Right now the docs are a bit thin.

The examples folder has a few examples: https://github.com/bitfinexcom/bitfinex-api-node/tree/master/examples

You can also take a look at our API docs: https://bitfinex.readme.io/v2/reference#ws-auth-position -- much of the API functionality is covered by this API client. The Websocket V2 functionality is covered here: https://github.com/bitfinexcom/bitfinex-api-node/blob/master/ws2.js - there you will find the `submitOrder` function:

https://github.com/bitfinexcom/bitfinex-api-node/blob/1bcbe1e67d4fccb911e1e811d8382669eda2c02b/ws2.js#L257-L259

The function delegates to a function called `send`, which pushing the data directly into the open Websocket: 

https://github.com/bitfinexcom/bitfinex-api-node/blob/1bcbe1e67d4fccb911e1e811d8382669eda2c02b/ws2.js#L211-L114

That means to submit an order, we can use the JSON from the V2 API docs for orders:

https://bitfinex.readme.io/v2/reference#ws-input-order-new

I will put together some examples for authenticated calls with an order tonight or tomorrow.

**Comment by TestniTester** [comment]
some examples would be great :+1:

**Comment by androng** [comment]
Here is an example for submitting an exchange limit order https://github.com/bitfinexcom/bitfinex-api-node/pull/103

**Comment by TestniTester** [comment]
can anyone give any help?
i want to buy/sell but whatever i set to type in params i get Invalid order type
im looking here
https://bitfinex.readme.io/v2/reference#ws-input-order-new
doin autehtification ok (i can get open orders, wallets but just cannot manage to buy/sell anything :)

**Comment by androng** [comment]
Here is an example for submitting an exchange limit order. What does it return? https://github.com/bitfinexcom/bitfinex-api-node/pull/103/commits/98545e8eceeded6cc3e81aaac8373c079d121bec

**Comment by nedievas** [comment]
Here is an example:
```
var order = [
  0,
  'on',
  null,
  {
    type: 'EXCHANGE LIMIT',
    symbol: 'tBTCUSD',
    amount: '0.01',
    price: '0.01',
    hidden: 0,
    postonly: 0
  }
]
bws.on('open', () => {
  bws.auth()
})
bws.on('auth', () => {
  bws.submitOrder(order)
  console.log('Order submitted')
})
```

**Comment by TestniTester** [comment]
i see "order submitted" but i dont see the order in my account ....
hmm
how can i get callback result ?

**Comment by nedievas** [comment]
Strange, because I see order in my account.

**Comment by TestniTester** [comment]
all i did was chainge symbol to tBTCXRP but with no callback i dont know whats going on,,,
ok you make your orders, do you have a callback working?

**Comment by nedievas** [comment]
There is no such pair!

**Comment by TestniTester** [comment]
what do you mean?
BTC=>bitcoin
XRP=>ripple
on bitfinex ?
of course there is?

**Comment by androng** [comment]
The pair is called tXRPBTC, not tBTCXRP. Check your websocket error
messages by adding the error callback.

On Sep 17, 2017 12:13, "TestniTester" <notifications@github.com> wrote:

what do you mean?
BTC=>bitcoin
XRP=>ripple
on bitfinex ?
of course there is?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/bitfinexcom/bitfinex-api-node/issues/114#issuecomment-330074819>,
or mute the thread

**Comment by TestniTester** [comment]
guys is there any other way i can make buy/sell... then using websockets ?
or if i reform my question..... api is now going from V1 to V2 if i understand correctly?
when will be there some documentation for V2?

**Comment by TestniTester** [comment]
a simple V2 post example would be really nice...
cos from that example i can make virtualy evrithing from v2 docs right?

**Comment by robertkowalski** [comment]
hey,

sorry i was caught in the smidgen release (https://github.com/bitfinexcom/smidgen)

the v2 api docs can be found here: https://docs.bitfinex.com/v2/docs

i would recommend using websockets, but here is a rest v2 api example:

```js
const BFX = require('bitfinex-api-node')

const API_KEY1 = 'some'
const API_SECRET1 = 'secret'

const opts = { version: 2, transform: true }

const bhttp = new BFX(API_KEY1, API_SECRET1, opts).rest

bhttp.alertList('price', (err, da) => {
  console.log(err, da)
})
```

**Comment by robertkowalski** [comment]
hey, i just opened a PR with an open order / cancel order example

https://github.com/bitfinexcom/bitfinex-api-node/pull/122
