### ISSUE TITLE
issue with orders

### ISSUE THREAD

**Issue by robertkowalski** [bitfinexcom/bitfinex-api-node#117]
came via email:

What is the status of the v2 WS support?

Did you notice that on failed new order, there is no usable information coming in the websocket? No order id or anything that identify what is really happened with which order.

**Comment by robertkowalski** [comment]
the response is added in the next api release

**Comment by jantielens** [comment]
Aha, so  for now it is normal that there is no error/info returned when you submit for example a new order and the API key is readonly?
Thanks for confirming, so I don't have to look in my code/setup for errors. :)

**Comment by robertkowalski** [comment]
hi @jantielens,

this issue describes a missing message when an order submission has **failed**

in all other cases yo should get a response.

**Comment by Andytreee** [comment]
hi @robertkowalski ,
is there any sample on submit new orders  for  WS v1

**Comment by f3rno** [comment]
Closing as the order notifications seem to handle this in the latest ws2
