### ISSUE TITLE
How to change an order?

### ISSUE THREAD

**Issue by algotek** [bitfinexcom/bitfinex-api-node#124]
How to change the price of a limit order?

**Comment by robertkowalski** [comment]
hi and thank you for your request!

you basically have to cancel the order and then create a new one.

there is a multi-operations endpoint which makes it quite handy to do that in one request, in the right order: https://docs.bitfinex.com/v2/reference#ws-input-order-multi-op

**Comment by algotek** [comment]
The cancel/open , especially with the multi-op is not working, and hit a " not enough exchange balance " error. 
Please suggest something else, or solve the "not enough exchange balance " error.

**Comment by nedievas** [comment]
it works in [REST1](https://docs.bitfinex.com/v1/reference#rest-auth-replace-order)

**Comment by algotek** [comment]
It does not work with REST1 either.  (/v1/order/cancel/replace).
That run into "not enough balance" also.

**Comment by nedievas** [comment]
Do you really have enough balance when testing?

**Comment by algotek** [comment]
Just to clarify, the cancel is successful, the 'not enough balance' come at the re-open phase.

**Comment by nedievas** [comment]
Just to clarify. Do you really believe that you have enough balance? You are changing the price, so you change the total of your order...

**Comment by algotek** [comment]
The price is lowered, if that helps.

**Comment by algotek** [comment]
Are you a bfx staff, or just a normal user?

**Comment by nedievas** [comment]
normal user. Will do test my self.

**Comment by nedievas** [comment]
Works like a charm: 
First buy 0.1 0.1
```
 node rtest.js
exec { id: 4022372229,
  cid: 70316413273,
  cid_date: '2017-09-27',
  gid: null,
  symbol: 'btcusd',
  exchange: 'bitfinex',
  price: '0.1',
  avg_execution_price: '0.0',
  side: 'buy',
  type: 'exchange limit',
  timestamp: '1506540716.536721257',
  is_live: true,
  is_cancelled: false,
  is_hidden: false,
  oco_order: null,
  was_forced: false,
  original_amount: '0.1',
  remaining_amount: '0.1',
  executed_amount: '0.0',
  src: 'api',
  order_id: 4022372229 }
```
let's change price to 0.05:
```
 node rtest.js
exec { id: 4022424576,
  cid: 70581520877,
  cid_date: '2017-09-27',
  gid: null,
  symbol: 'btcusd',
  exchange: 'bitfinex',
  price: '0.05',
  avg_execution_price: '0.0',
  side: 'buy',
  type: 'exchange limit',
  timestamp: '1506540981.58890109',
  is_live: true,
  is_cancelled: false,
  is_hidden: false,
  oco_order: null,
  was_forced: false,
  original_amount: '0.1',
  remaining_amount: '0.1',
  executed_amount: '0.0',
  src: 'api',
  order_id: 4022424576 } 
```
![capture](https://user-images.githubusercontent.com/6176288/30933992-d7d303c2-a3d4-11e7-9b77-c45694ac75fd.PNG)

**Comment by algotek** [comment]
When you test, make sure you do not have 2x the balance for the order. 
Let's say you have 1.9 BTC, open an order for 1 BTC, and try the REST1 replace.
The "not enough balance" will be hit regularly.

**Comment by nedievas** [comment]
Do you use `use_remaining: true` in params?

**Comment by algotek** [comment]
" use_remaining boolean True if the new order should use the remaining amount of the original order."
Since the order not filled/part filled, the remaining amount is the same as the original amount, how would this help? (I'll go an try, but don't see the logic..)

**Comment by nedievas** [comment]
I suppose if `false`, it opens new order then cancels the old one...

**Comment by nedievas** [comment]
the amount is frozen though, when you have open order.

**Comment by algotek** [comment]
It did not helped, the trading engine lose track of the balance eventually.

**Comment by nedievas** [comment]
I suppose it's your side problem. Simple code is working.

**Comment by algotek** [comment]
Did you make sure there is no 2x balance during the test? Do you understand what that means?
The trading engine can't calculate the balance requirement fast enough, that is what I experience.

**Comment by nedievas** [comment]
My start balance for test $0.14.
Buy 1 BTC for $0.13:
```
node rtest.js
exec { id: 4028980776,
  cid: 17524682175,
  cid_date: '2017-09-28',
  gid: null,
  symbol: 'btcusd',
  exchange: 'bitfinex',
  price: '0.13',
  avg_execution_price: '0.0',
  side: 'buy',
  type: 'exchange limit',
  timestamp: '1506574324.720531356',
  is_live: true,
  is_cancelled: false,
  is_hidden: false,
  oco_order: null,
  was_forced: false,
  original_amount: '1.0',
  remaining_amount: '1.0',
  executed_amount: '0.0',
  src: 'api',
  order_id: 4028980776 }
```
Changing order to 1 BTC for $0.12:
```
 node rtest.js
Error: Invalid order: not enough exchange balance for 1.0 BTCUSD at 0.12
    at Request.request [as _callback] (/home/nedievas/zenbot/node_modules/bitfinex-api-node/rest.js:61:17)
    at Request.self.callback (/home/nedievas/zenbot/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/home/nedievas/zenbot/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/home/nedievas/zenbot/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
Ups...

**Comment by algotek** [comment]
> hi and thank you for your request!
> you basically have to cancel the order and then create a new one.
> there is a multi-operations endpoint which makes it quite handy to do that in one request, in the right order: https://docs.bitfinex.com/v2/reference#ws-input-order-multi-op



> robertkowalski
>   
> 
>     
> 
>     commented
> 
>     a day ago
> 
> 
> 
>   
> 
> 
> 
>   
>     
>       
>         
>           
>               hi and thank you for your request!
> you basically have to cancel the order and then create a new one.
> there is a multi-operations endpoint which makes it quite handy to do that in one request, in the right order: https://docs.bitfinex.com/v2/reference#ws-input-order-multi-op

Who is in charge of this? Could you point out the trading engine developers on github?

**Comment by LRonHubs** [comment]
Yes I also get this error, bitfinex is extremely slow to update balances available balances. Have you checked your available balance between endpoints? When I do, I still get a "not enough balance error", even if the "update balance" endpoint says I have enough.

**Comment by LRonHubs** [comment]
@nedievas  I'm assuming you have > $0.27 in your total balance on bitfinex, yes? Because if so, your test case doesn't work.

**Comment by LRonHubs** [comment]
https://github.com/bitfinexcom/bitfinex-api-node/issues/141
