### ISSUE TITLE
STOP LIMIT FUNCTION IN API

### ISSUE THREAD

**Issue by g666nz** [bitfinexcom/bitfinex-api-node#125]
I noticed in the Bitfinex documents there was no stop limit option. I was wondering if that was a problem in the documentation, or you do not provide that on your api. Hope to hear from you soon.

**Comment by nedievas** [comment]
I thing you must provide it in your order `type` as:

> Either “market” / “limit” / “stop” / “trailing-stop” / “fill-or-kill” / “exchange market” / “exchange limit” / “exchange stop” / “exchange trailing-stop” / “exchange fill-or-kill”. (type starting by “exchange ” are exchange orders, others are margin trading orders)

REST: 
```
rest.prototype.new_order = function (symbol, amount, price, exchange, side, type, is_hidden, postOnly, cb) { ....
```
WS2: 
```
var order = [ 0, 'on', null, { 'gid': 1, 'cid': 1. 'type': 'LIMIT', 'symbol': 'tBTCUSD', 'amount': '1.0', 'price': '200', 'hidden': 0 } ] 
submitOrder (order) {
    this.send(order)
} 
```

**Comment by g666nz** [comment]
Yes but you only have the exchange stop option. Limit is a basic LIMIT(is for margin trading) and exchange LIMIT is for basic exchange trading. However there is no 'EXCHANGE STOP-LIMIT' or 'STOP-LIMIT'(For margin trading'. 

So is that option missing from the documentation or is it not available over the API.

**Comment by nedievas** [comment]
It is available as `type`. Please read [Request Fields for WS2](https://docs.bitfinex.com/v2/reference#ws-input-order-new). It's up to you what type of order to do.

**Comment by g666nz** [comment]
I'm using v1 REST. Is it possible with that or will i have to update to V2. 

“market” / “limit” / “stop” / “trailing-stop” / “fill-or-kill” / “exchange market” / “exchange limit” / “exchange stop” / “exchange trailing-stop” / “exchange fill-or-kill”. (type starting by “exchange ” are exchange orders, others are margin trading orders)

There is a "stop" and "exchange stop" but no "stop limit" and "exchange stop limit" which is available to use on the bitfinex dashboard. So do i have to upgrade to v2?

**Comment by nedievas** [comment]
Check [this](https://docs.bitfinex.com/v1/reference#rest-auth-new-order) and make a test yourself. It's only as parameter with is send to Bitfinex server. You may send it without this API.

**Comment by g666nz** [comment]
I'l give it a test.

**Comment by g666nz** [comment]
hey tried to make the type, stop-limit. Did not work, I guess it's not in the API.
