### ISSUE TITLE
Need Help With Public REST documentation

### ISSUE THREAD

**Issue by AscensionProtocol** [bitfinexcom/bitfinex-api-node#129]
Hello!

I am sorry if this has been asked before, but is there documentation for how to properly implement V2 of the REST client? 

For example I do:

`import BFX from 'bitfinex-api-node'

const API_KEY = 'secret'
const API_SECRET = 'secret'

const options = {
  version: 2,
  transform:true
}
const bw = new BFX(API_KEY, API_SECRET, options)
const bfw_rest = bw.rest

... but then for my implementation, I get it wrong here:

 bfw_rest.ticker('BTCUSD', (error, data) => {
        console.log('success ',data, error)
    })  
`

Thank you for the help! :)

**Comment by f3rno** [comment]
The symbol needs to be prefixed with a 't', so `'tBTCUSD'` instead of `'BTCUSD'`.

The repo docs definitely need more attention, coming soon ;)
