### ISSUE TITLE
Can't close remaining margin position: "Invalid order, minimum size for ...."

### ISSUE THREAD

**Issue by algotek** [bitfinexcom/bitfinex-api-node#130]
When the margin position fall below the minimum opening size, how to close the position? (The web gui can close it)

**Comment by f3rno** [comment]
Closing due to age, but for others in the future: Add the `POS_CLOSE` flag to the closing order: https://github.com/bitfinexcom/bitfinex-api-node/blob/master/lib/models/order.js#L339
