### ISSUE TITLE
Authentication and list of authenticated endpoints for rest API (v1)

### ISSUE THREAD

**Issue by hoangnguyen208** [bitfinexcom/bitfinex-api-node#131]
The tutorial for web socket in the documentation is quite clear, but I could not find any examples from the docs on how to authenticate with API keys as well as authenticated endpoints for rest API. I'm not sure but I'm guessing authentication function could be brest.makeAuthRequest(), and an endpoints for key permissions could be brest.keyinfo(). However, it would be great if the team produce a full version of documentation. Thank you.

**Comment by f3rno** [comment]
Docs have been updated for [REST2](https://github.com/bitfinexcom/bitfinex-api-node/blob/master/doc/rest2.md) and [WS2](https://github.com/bitfinexcom/bitfinex-api-node/blob/master/doc/ws2.md) and examples are available [here](https://github.com/bitfinexcom/bitfinex-api-node/tree/master/examples).

It should also be noted that the client implementations are fairly straightforward (especially REST), so when in doubt don't be afraid to check the source.

As for v1, it is deprecated and will be removed in the future (both REST and WS).
