### ISSUE TITLE
v1 api parsed incorrectly

### ISSUE THREAD

**Issue by shimondoodkin** [bitfinexcom/bitfinex-api-node#133]
I had just connected, authenticated, subscribed to ws, logged the arguments
the ws called several times
ws: function arguments = { '0': 'exchange' }
ws: function arguments = { '0': 'USD' }
ws: function arguments =  { '0': 435.30566562 }
ws: function arguments = { '0': 0 }

```javascript

API_KEY='...';
API_SECRET='...';

const BFX = require('bitfinex-api-node')
const opts = { version: 1, transform: true};
var bitfinexws = new BFX(API_KEY, API_SECRET, opts).ws;
        bitfinexws.on('auth', () => {
          console.log('authenticated')
        })

        bitfinexws.on('open', () => {
          console.log('bitfinexws open')
          bitfinexws.auth()
        })

        bitfinexws.on('close', () => {
          console.log('bitfinexws close')
        });

        bitfinexws.on('error', (error) => {
          console.log('bitfinexws error',error.stack)
        });
       bitfinexws.on('ws', function(wallets_in) {
        console.log('ws:', arguments)
        });
```

**Comment by robertkowalski** [comment]
hmm... we don't expose a `ws` event - what do you want to achieve?

the code example seems to be incomplete. on a run i get:

```
bitfinexws open
bitfinexws error undefined
```

**Comment by shimondoodkin** [comment]
wallet snapshot
https://bitfinex.readme.io/v1/reference#ws-auth-wallet-snapshot

**Comment by f3rno** [comment]
@shimondoodkin you would need to listen for a `ws` message here, apologies for the late reply.

Specifically, something along the lines of `ws.on('message', (msg) => ...` where `msg[1]` is `ws`, at least for ws v2. Closing as this is not an issue with this repo.
