### ISSUE TITLE
REST v1 - Withdrawal endpoint & automation

### ISSUE THREAD

**Issue by pipobimbo** [bitfinexcom/bitfinex-api-node#134]
Is there any way to use the Withdrawal end point (REST v1) without having to confirm each individual withdrawal by email? The previous fairly limit the usefulness of this endpoint / makes it difficult to automate some processes.

Thanks.

**Comment by LRonHubs** [comment]
Yea these are called the "Conditions for auto-withdrawal processing" on the Bitfinex Webpage. Go there, click Withdrawal, click BTC, and you'll see a checkbox listing the stuff you need to get it done automagically... Good luck

**Comment by brentkirkland** [comment]
@robertkowalski I think this can be closed
