### ISSUE TITLE
Websocket connection silently stops receiving data

### ISSUE THREAD

**Issue by LRonHubs** [bitfinexcom/bitfinex-api-node#138]
My orderbook websockets occasionally stop receiving data, similar to this error in the Go API: https://github.com/bitfinexcom/bitfinex-api-go/pull/30

I was wondering if there was an ability to set a timeout so that an error may be thrown when a message is not received for some time? Or better yet, if it could automatically reconnect when a message is not received after some time? 

Thanks

**Comment by LRonHubs** [comment]
https://github.com/bitfinexcom/bitfinex-api-node/issues/112

**Comment by includeleec** [comment]
do you resolve now?

**Comment by LRonHubs** [comment]
No, i stopped trading on bitfinex because of this and many other issues

**Comment by gandac** [comment]
Hey,
I reconnect on 'error' and 'close' events. I don't know if this is the correct mode to reconnect, but seems it works for me.

```
var bws = new BFX(API_KEY, API_SECRET, opts).ws;

bws.on('error', ()=>{bws = new BFX(API_KEY, API_SECRET, opts).ws} );

bws.on('close', ()=>{bws = new BFX(API_KEY, API_SECRET, opts).ws} );
```

**Comment by nemozny** [comment]
@gandac I tried this, but it doesn't work for me. 
It says

1. Bitfinex server restarted
2. I close and reopen connection
3. Subscribed candles
4. All subscribes fail and never revives until I manually kill and start the process.

**Comment by jsappme** [comment]
any solution for this?

**Comment by ferittuncer** [comment]
I have the same issue.

**Comment by f3rno** [comment]
I'm late to this, but; @ferittuncer have you tried using the packet watchdog option? It resets the connection if no packet is received within the watchdog window.

**Comment by ferittuncer** [comment]
@f3rno Thanks. Can you explain in detail please?
