### ISSUE TITLE
REST v1 API. add params 'limit_trades' in method "Trades" for public 

### ISSUE THREAD

**Issue by steeply** [bitfinexcom/bitfinex-api-node#139]
quotation from a letter from bitfinex

> Trades (/v1/trades): The default response will return the last 100 trades instead of 1000. The "limit_trades" option will remain available to request a custom number of trades.

**Comment by f3rno** [comment]
@steeply Hey, apologies for the late response, v1 is really low priority for us atm.

We could refactor the v1 REST methods, but that would break compatibility with existing code, and a `limit` param is available on v2 REST here: https://github.com/bitfinexcom/bitfinex-api-node/blob/master/rest2.js#L135

tl;dr this should be changed, but v1 is now deprecated, please use v2
