### ISSUE TITLE
Trades not matching the orderbook

### ISSUE THREAD

**Issue by aldanor** [bitfinexcom/bitfinex-api-node#140]
Here's a little node script based on one of the scripts in `examples/` that tries to build the book and report in red any trade events that don't seem to match anything that exists in the orderbook: https://gist.github.com/aldanor/5da8bfb27c592edcdab0aefdca650a95 (normally this would happen within a minute or so).

Here's a typical example:

```
Order book: [ 6386.9, 0, 1 ]  <---- 6386.9 price point removed here
Order book: [ 6386.5, 0, 1 ]
Order book: [ 6386.6, 2, 0.01799334 ]
Order book: [ 6375.6, 1, 0.2 ]
Order book: [ 6372.1, 1, 0.10438114 ]
Order book: [ 6394.8, 0, -1 ]
Order book: [ 6389.6, 1, -0.2 ]
Order book: [ 6392.5, 2, -0.505 ]
Trade: [ 'te', [ 83332892, 1509491264000, -0.1993203, 6386.9 ] ]  <---- ??
Trade: [ 'tu', [ 83332892, 1509491264000, -0.1993203, 6386.9 ] ]
Order book: [ 6378.5, 0, 1 ]
Order book: [ 6378.3, 0, 1 ]
Order book: [ 6375.6, 0, 1 ]
Order book: [ 6386.9, 2, 4.3006797 ]  <----  ?? also, "2"?
```

Seems like just before the match event occurred, there was already two orders with total size of `4.3006797 + 0.1993203 = 4.5` on the orderbook, however the last known book event claims it's zero, i.e. that the price point doesn't even exist.

**Comment by LRonHubs** [comment]
https://github.com/bitfinexcom/bitfinex-api-node/issues/138 ?

**Comment by aldanor** [comment]
Nope. Websocket connection is fine. It looks like Bitfinex seems to not the synchronise the two channels properly (unlike all other major exchanges I’m aware of).

**Comment by f3rno** [comment]
Aye, this is not an issue with the client library
