### ISSUE TITLE
Error: connect ETIMEDOUT 104.16.171.181:443

### ISSUE THREAD

**Issue by includeleec** [bitfinexcom/bitfinex-api-node#142]
> Error: connect ETIMEDOUT 104.16.171.181:443
>     at Object.exports._errnoException (util.js:1033:11)
>     at exports._exceptionWithHostPort (util.js:1056:20)
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1105:14)

always occur.

**Comment by includeleec** [comment]
i run code in visual studio code error,but run in bitfinex api web playground is ok.
why??

**Comment by brentkirkland** [comment]
Could you post a snippet of the code you are executing?

**Comment by includeleec** [comment]
```
bfx.ws.on('open',function() {
    bfx.ws.auth()
    bfx.ws.subscribeOrderBook('ETHUSD')
})

bfx.ws.on('message', (msg) => {
   ....
})

bfx.ws.on('orderbook', (pair, book) => {
   ....
})
```

**Comment by f3rno** [comment]
Is this still happening?
