### ISSUE TITLE
Socket hung up error

### ISSUE THREAD

**Issue by xitter** [bitfinexcom/bitfinex-api-node#144]
I am connecting to bifinex socket and after a certain time, I get the socket hung up error. How to handle this error and reconnect to the socket. This can be a feature inside this library only.

ERROR:
```
Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at TLSSocket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by sjashwin** [comment]
Could you provide some steps to reproduce this error?

**Comment by xitter** [comment]
Error occurs when socket remains open for a long period of time.

Reproduce: 
Initialize ws `const bws = new BFX(API_KEY, API_SECRET, opts).ws` and keep this open for a long time, hung up error will appear.

**Comment by gandac** [comment]
Initialize with a variable not a const , then I reconnect on 'error' and 'close' events. I don't know if this is the correct mode to reconnect, but seems it works for me.

```
var bws = new BFX(API_KEY, API_SECRET, opts).ws;

bws.on('error', ()=>{bws = new BFX(API_KEY, API_SECRET, opts).ws} );

bws.on('close', ()=>{bws = new BFX(API_KEY, API_SECRET, opts).ws} );
```

**Comment by f3rno** [comment]
@gandac your snippet doesn't reconnect, it spawns a new ws connection.

Have a look at the reconnect logic from the v2 release:

```js
  /**
   * Utility method to close & re-open the ws connection. Re-authenticates if
   * previously authenticated
   *
   * @return {Promise} p - resolves on completion
   */
  reconnect () {
    if (!this._ws) return this.open()

    return new Promise((resolve, reject) => {
      this._ws.once('close', () => {
        this.open()

        if (!this._wasEverAuthenticated) {
          return resolve()
        }

        this._ws.once('open', this.auth.bind(this))
        this._ws.once('auth', () => resolve())
      })

      this.close()
    })
}
```

**Comment by jsappme** [comment]
any plan on fixing the reconnection not working?
