### ISSUE TITLE
Examples are inconsistent with Readme and Docs

### ISSUE THREAD

**Issue by 360disrupt** [bitfinexcom/bitfinex-api-node#15]
## Readme:

`bitfinexWebsocket = bitfinexApiNode.websocket`
- requiring with `.websocket`
- no info on init
## [Example](https://github.com/bitfinexcom/bitfinex-api-node/blob/master/examples/websockets.js#L1):

```
var BitfinexWS = require ('bitfinex-api-node').WS;
var bws = new BitfinexWS();
```
- requiring with `WS`
- init without key & secret
## Docs

`new BitfinexWS(APIKey, APISecret)`
- init with key & secret

Looking into the index.js reveals how it should be used:

```
BitfinexApi = require('bitfinex-api-node');
bitfinexApi = new BitfinexApi(options.apiKey, options.apiSecret);
bitfinexWebsocketApi = bitfinexApi.ws;
bitfinexRestApi = bitfinexApi.rest;
```

**Comment by yagop** [comment]
Both can be used

https://github.com/bitfinexcom/bitfinex-api-node/blob/master/index.js

**Comment by robertkowalski** [comment]
we improved the docs, examples and the code with version 1.0.0, it is available on npm now.

hope you enjoy it! :)
