### ISSUE TITLE
Example for submiting a limit order and tracking it

### ISSUE THREAD

**Issue by leandrodvd** [bitfinexcom/bitfinex-api-node#153]
Hi,

I'm trying to write some code to submit a limit order and track it so that I can trigger another action when the order gets executed or cancel the order if it doesn't get executed after some time.

There is a code in the examples directory that shows how to submit an order and how to cancel it, but how can I track the status of that order at any time ?

**Comment by f3rno** [comment]
Hi,

So this is a bit opaque at the moment, but you need to listen for messages on the ws stream referencing the order you initially created (`ou` for updates, `oc` for close) to pick up status updates. I'm working on a `ws2` refactor which will help with this via `order.submit().then(..` and `order.onUpdate`, but it's still in the pipeline.

In terms of not having an `id` before order creation, you can specify a `cid` and then listen for `ou` & `oc` (and `on`) packets with matching `cid`s.

**Comment by leandrodvd** [comment]
Thanks for the reply,

So if I miss the order update in the stream there is not way today to "ask" for the order details, right ?

**Comment by f3rno** [comment]
At the moment, there is sadly no way besides catching the update packets when they arrive. So you need to listen on the stream for the relevant events and update your local order accordingly. An `on-req` notification is fired off for each new order on submit, along with an `on`/`ou`/`oc` packet depending on if the order fills instantly or not (notification is always first).

After that updates come in via `ou` or `oc` (the latter in case the order closes)

**Comment by leandrodvd** [comment]
Ok, thanks for the confirmation @f3rno

**Comment by dutu** [comment]
well, you can always use REST to get the order status at anytime

**Comment by GregTheGreek** [comment]
@leandrodvd @f3rno 
Do you guys know if `te` represents that the order was filled? Or does it simply mean it is open?

**Comment by f3rno** [comment]
@GregTheGreek `te` represents a trade, for order status you should monitor `on`, `ou`, and `oc` messages. `ou` are for order updates, you can check the values of `amount`& `amountOrig` along with `status` to detect a fill. Same thing with `oc` which afaik can happen for order executions & cancellations.

**Comment by GregTheGreek** [comment]
@f3rno thanks for clearing that up.. Is there anywhere that explicitly explains what the returned status codes would look like? I,e options for `status`. Could not find anything here or on the docs.bitfinex.com. Thanks again

**Comment by f3rno** [comment]
@GregTheGreek eh, they get concatenated on the server. At first the `status` string from an `ou` packet may be `'PARTIALLY FILLED @ 586.06(0.85)'`, and then from the following `oc` it could be `'EXECUTED @ 586.86(0.05): was PARTIALLY FILLED @ 586.06(0.85)'`

So you can split on `:` and check the first substring for `'EXECUTED'`or `'CANCELED'`, etc, or check the entire status string knowing that cancelled/executed are final states.

**Comment by GregTheGreek** [comment]
Is there anywhere that shows an example payload from the server?
I've seen this, but I was wondering if there is something more specific?
`bws.on('message', (msg) => {
  if (!Array.isArray(msg)) return

  const [ , type, payload ] = msg
`

**Comment by f3rno** [comment]
The docs have payload 'schemas' for each message type: https://docs.bitfinex.com/v2/reference#ws-public-candle You can switch between snapshots/updates on the right for each type.

Or you can check the `lib/models/` folder in the PR I referenced above

**Comment by GregTheGreek** [comment]
@f3rno Thank you!

**Comment by GregTheGreek** [comment]
@f3rno By default does this package use V1 or V2? 

I ask this because V1 supports `ou`,`oc` where V2 does not explicitly say in the documentation that it supports them.
