### ISSUE TITLE
Can I change the delay between getting the tickers update when subscribed to tickers ? 

### ISSUE THREAD

**Issue by Miguelme** [bitfinexcom/bitfinex-api-node#163]
I'm subscribed to a ticker and I would like to change the time when I get the new ticker because currently is in 10 seconds and I would like it to be around 60 seconds between the updates. Is there some info anywhere on how to do this ? Is it possible ?

**Comment by f3rno** [comment]
@Miguelme you can't change the server update interval, but you can either ignore every intermediate update or keep the last value and work with that every 60 seconds.

I'm closing this as it isn't an issue with the repo, let me know if you need any more info.
