### ISSUE TITLE
bws.send callback?

### ISSUE THREAD

**Issue by StyleShit** [bitfinexcom/bitfinex-api-node#165]
How can I use a callback function in the websocket "send()" method?
I wanna execute some code after the data has been sent and the order was created.

**Comment by f3rno** [comment]
@StyleShit this isn't possible at the moment, but it is implemented as a `Promise` in the 2.0.0-beta update for some events. (See https://github.com/bitfinexcom/bitfinex-api-node/pull/155)

A solution in the meantime is to listen for notifications on the auth channel (0), and check for `on-req` messages:

```[ 0,
  'n',
  [ null,
    'on-req',
    null,
    null,
    [ 1149684455,
      null,
      1512233308484,
      'tBTCUSD',
      null,
      null,
      0.1,
      0.1,
      'EXCHANGE LIMIT',
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      1165.6,
      null,
      null,
      null,
      null,
      null,
      null,
      0,
      null,
      null ],
    null,
    'SUCCESS',
    'Submitting exchange limit buy order for 0.1 BTC.' ] ]```
