### ISSUE TITLE
Is there an option to always retrieve the orderbook snapshot?

### ISSUE THREAD

**Issue by wadami** [bitfinexcom/bitfinex-api-node#168]
Hello,

It would be easier if we could always retrieve the orderbook snapshot and limit the returned values or have fixed options for that (like 5, 10, 20 and full).
Some other exchanges already provides it in their APIs.

Thanks.

**Comment by f3rno** [comment]
@wadami for performance & bandwidth reasons, no, but we've added `manageOrderBooks` in the updated `WSv2` client, which does exactly this. You can find a full example here: https://github.com/bitfinexcom/bitfinex-api-node/blob/master/examples/ws2/order_books.js

**Comment by wadami** [comment]
I'm using pure javascript, is it a correct implementation?
`ws = new WebSocket('wss://api.bitfinex.com/ws/2');
ws.onopen = function() {
	ws.send(JSON.stringify({"event":"subscribe", "channel":"book", "manageOrderBooks":"true", "transform":"true", "symbol":"tBTCUSD", "prec":"R0", "len":"25"}));
};
ws.onmessage = function(msg) {
	var response = JSON.parse(msg.data);
	console.log(response);
}`

I'm getting only the updates yet.

**Comment by f3rno** [comment]
@wadami have a look at the examples: https://github.com/bitfinexcom/bitfinex-api-node/tree/master/examples/ws2
