### ISSUE TITLE
lack `payment_id` ripple cannot withdraw

### ISSUE THREAD

**Issue by zhaoxiongfei** [bitfinexcom/bitfinex-api-node#170]
https://github.com/bitfinexcom/bitfinex-api-node/blob/222de2a04d7e752b954602c0dce7e2e01627029b/rest.js#L422

**Comment by f3rno** [comment]
This has been fixed in `v2.0.0-beta`, which is now released.

The v1 `withdraw` method has been added to `RESTv2` w/ a full params object. Docs [here](https://github.com/bitfinexcom/bitfinex-api-node/blob/master/doc/rest2.md#RESTv2+withdraw)

**Comment by zhaoxiongfei** [comment]
`rest.prototype.withdraw = function (withdraw_type, walletselected, amount, address, paymentId, cb) {
  const params = {
    withdraw_type,
    walletselected,
    amount,
    address
  }
  if (paymentId) params.payment_id = paymentId;
  return this.make_request('withdraw', params, cb)
}`

Can I modify it like this?

**Comment by f3rno** [comment]
@zhaoxiongfei yes, that also works 🙂

**Comment by zhaoxiongfei** [comment]
@f3rno Thank you.
