### ISSUE TITLE
Please add onTicker example to docs - help needed

### ISSUE THREAD

**Issue by s5m4** [bitfinexcom/bitfinex-api-node#174]
hi all, 
I cannot figure out how to read and process data that is emitted by a subscribed ticker channel using the ws.on() or ws.onTicker() functions. 

It used to work like this for a established websocket connection: 
```    
ws.on('ticker',` (pair, ticker) =>{
        console.log('Ticker pair:',pair)
        console.log('Ticker data',ticker)}
```
which now results in 'undefined' where the ticker data would have been in the console output. 

I found the example for the onTrades() function and figured onTicker() must work similarly as the /doc/ws2.md describes them very similarly. 

So I tried to change the onTrades() example from the examples/ws2/trades.js from (slightly adjusted):

    const BFX = require('bitfinex-api-node')

    const bfx = new BFX({
      apiKey: '...',
      apiSecret: '...'
     })
    const ws = bfx.ws(2)

    ws.on('open', () => {
      console.log('open')
      ws.subscribeTrades('tBTCUSD')
     })

    ws.onTradeEntry({ pair: 'BTCUSD' }, (trade) => {
      console.log('te: %j', trade)
    })

    ws.onTradeUpdate({ pair: 'BTCUSD' }, (trade) => {
      console.log('tu: %j', trade)
    })

    ws.onTrades({ pair: 'BTCUSD' }, (trades) => {
      console.log('trades: %j', trades)
    })

    ws.open()

to 

    const ws = bfx.ws(2)

    ws.on('open', () => {
      console.log('open')
     if(ws.subscribeTicker('tBTCUSD')) console.log('subscribed to BTCUSD Ticker')
    })

    ws.onTicker({ symbol: 'BTCUSD' }, (tickers) => {

      console.log('tickers: %j', tickers)
    })

    ws.open()

- which is not working, giving me an error

     if (Array.isArray(data[0])) {
    TypeError: Cannot read property '0' of undefined

How is it done? In the end I need to be able again to check on every ticker what symbol it is and act accordingly, like it used to work: 

    bws.on('ticker', (pair, ticker) => {
	    if (pair.toString()==='tBTCUSD'){
	    	//do this
	    } else if (pair.toString()==='tXMRBTC'){
                    //do that
    }

Thank you for your insights!

Kind regards,
stefan

**Comment by f3rno** [comment]
@s5m4 Good catch! This turned out to be a bug in ticker payload parsing, I've opened a PR with a fix.

You also have a bug in your logic, as the `onTicker` symbol needs to be prefixed with a 't' as well, like `tBTCUSD`. Working example w/ PR fix:

```
const SYMBOL = 'tIOTEUR'
const ws = bfx.ws(2)

ws.on('open', () => {
  console.log('open')
  ws.subscribeTicker(SYMBOL)
})

ws.onTicker({ symbol: SYMBOL }, (ticker) => {
  console.log('%s ticker: %j', SYMBOL, ticker)
})

ws.open()
```

**Comment by s5m4** [comment]
@f3rno thanks for the quick response, that's good news! 
Now what I'm still wondering is how I can check what symbol/pair the ticker is of from WITHIN the function, like stated above, what used to work like this: 
```
bws.on('ticker', (pair, ticker) => {
    if (pair.toString()==='tBTCUSD'){
    	//do this
    } else if (pair.toString()==='tXMRBTC'){
                //do that
}
```
The ticker object in your example doesn't contain the pair, adding "pair" in the argument list is not working accordingly. However there is this new '{ symbol: 'tXMRBTC' }' block, any way I can read this from within the function, somehow like this:
```
ws.onTicker( {}, (ticker) => {
  if (symbol==='tBTCUSD'){
    	//do this
    } else if (symbol==='tXMRBTC'){
        //do that
})
```
Thank you again for your thoughts!

**Comment by wonder-wu** [comment]
thanks

**Comment by s5m4** [comment]
btw. if anyone encounters the same problem and is as unable as me to change the source code on a deeper level themselves, here is what I did now: 
I'm using both, the new 2.0.0 AND the previous versions in one application by having two modules, one which uses 2.0.0 for the new order handling with Order.js and the older version for working with the Tickers. 
Kind regards!

**Comment by f3rno** [comment]
@s5m4 this is on my radar and should be patched tomorrow.

**Comment by geekguy** [comment]
@f3rno - any eta for the fix to go live?

If not, any work around for this?

**Comment by s5m4** [comment]
@geekguy not sure what exactly you're referring to but check my previous comment. maybe it can help you. what's your issue precisely? Maybe I can share a thought.

**Comment by geekguy** [comment]
@s5m4 

We need to merge https://github.com/bitfinexcom/bitfinex-api-node/pull/176 in master.

Without that fix, socket ticker is not working. 

I wanted to know when are we planning to merge that branch.
