### ISSUE TITLE
Rename onTradeEntry to onTradeExecute

### ISSUE THREAD

**Issue by StyleShit** [bitfinexcom/bitfinex-api-node#177]
Hi,

I couldn't find any function for tradeExecute in the docs. Is there one?

**Comment by f3rno** [comment]
@StyleShit `onTradeEntry` and `onTradeUpdate`, `te` fires before `tu` and should be used for realtime data

Maybe `onTradeEntry` should be renamed to `onTradeExecute`, hmm.

**Comment by StyleShit** [comment]
@f3rno, tradeEntry means that the trade was executed? If so, I also think you should rename it.

**Comment by f3rno** [comment]
Fixed in `master`
