### ISSUE TITLE
Rest API Error: ESOCKETTIMEDOUT 

### ISSUE THREAD

**Issue by burzakovskiy** [bitfinexcom/bitfinex-api-node#18]
Function client.orderbook periodically throws error "ESOCKETTIMEDOUT"

**Comment by Onefivefournine** [comment]
Same here, but in client.tickers
Found out possible solutions here
https://github.com/bitpay/node-bitpay-client/issues/84
or here
https://stackoverflow.com/a/43857814/7430672
