### ISSUE TITLE
Incomplete examples

### ISSUE THREAD

**Issue by ir-fuel** [bitfinexcom/bitfinex-api-node#182]
Hi

I just stumbled upon this SDK and it's quite hard to understand how to use it, as the link between the docs/examples here and the docs on bitfinex is not really clear.
For example:

There is 1 code example that shows how to request a calc:

```
      ws.requestCalc([
        'margin_sym_tBTCUSD',
        'position_tBTCUSD',
        'wallet_margin_BTC',
        'wallet_funding_USD'
      ])

```

But nowhere is shown where the result of this request arrives.

I dug a bit in the documentation and I found this:
```
wSv2.onMessage(opts, cb)

opts	Object	
opts.cbGID	string	callback group id
cb	Method	

```

Which I presume might be the callback where messages are received, but there is no info to be found about what the signature is of the callback function.

Looking at the official docs I only see explanations on how to use their API via normal websockets or REST calls, not by using this abstraction.

Pretty confusing I must say.

**Comment by f3rno** [comment]
Fixed in `master`

**Comment by slidenerd** [comment]
I apologize if this is a silly question, I havent come across this calc thing on other exchanges, I read the docs here too https://docs.bitfinex.com/v2/reference#ws-input-calc what exactly is this calc for? to get interest rates for loaning crypto to other trades?

**Comment by f3rno** [comment]
@slidenerd the calcs it affects are usually performed async & on an interval; if you require an updated value immediately you can manually request a calc to be performed. It's used for position P/L, wallet balances (available vs total), and margin/funding stats (total borrowed/offered, etc)
