### ISSUE TITLE
What means this value?

### ISSUE THREAD

**Issue by 4sh3** [bitfinexcom/bitfinex-api-node#188]
I think the params are: [Price, Number of orders at this price, volume]

![image](https://user-images.githubusercontent.com/30200595/34909213-c6f1861a-f89c-11e7-8624-f3085f9f49a5.png)

**Comment by f3rno** [comment]
@4sh3 `const [price, count, amount] = entry`

https://github.com/bitfinexcom/bitfinex-api-node/blob/master/lib/models/order_book.js#L49
