### ISSUE TITLE
Rest v2 Trades and Orders history returns empty list

### ISSUE THREAD

**Issue by william20111** [bitfinexcom/bitfinex-api-node#197]
Hi,

```
https://api.bitfinex.com/v2/auth/r/trades/tETHUSD/hist
https://api.bitfinex.com/v2/auth/r/orders/tETHUSD/hist
```
#113 

I am experiencing the same as referenced in this bug. The fix mentioned in that bug seems to resolve it also. Rather than a empty payload using the "_bfx" seems to work.

`{"_bfx":1}`

Cheers
Will

**Comment by f3rno** [comment]
Hmm, I can't replicate now. In the future, try the `trades()` method from `RESTv2`:

```
  /**
   * @param {string} symbol
   * @param {number} start
   * @param {number} end
   * @param {number} limit
   * @param {Method} cb
   * @return {Promise} p
   * @see https://docs.bitfinex.com/v2/reference#rest-auth-trades-hist
   */
  trades (symbol = 'tBTCUSD', start = null, end = null, limit = null, cb) {
    return this._makeAuthRequest(`/auth/r/trades/${symbol}/hist`, {
      start, end, limit
    }, cb, Trade)
  }
```

**Comment by masterkain** [comment]
hello, I just closed another ticket that might be related to this.

During tests `v2/auth/r/trades/hist` returns only recent trades, but when I try to ask for a range I get nothing in return.
Initially I was thinking that `end` and `start` were an issue, but I got recent trades in return when specifying them.

https://gist.githubusercontent.com/masterkain/105396aef86d80d60431f33b06f45708/raw/f547992ab7adc609e1e353c2fd187519046782f8/gistfile1.txt

This is a replay cassette of the http interations, I started one year ago and fragmented the start/end apart in 3 months blocks. Only the recent ones goes returned but I have a lot of trades of all kinds starting Aug 2017.

Are you able to fetch historical trades using end/start?

**Comment by spig0t** [comment]
I'm trying to use all three potential methods I can see to get some order history - rest1's past_trades, rest2's trades + orderHistory .... and none of them return any results (just empty arrays), even though I just made a trade some minutes ago (which shows in my "Order History" on the bitfinex website) to be sure I have at least one recent-enough trade (I have plenty of older ones but I understand it might be expected that nothing you do through the API can fetch those) .... 

I tried using both e.g. 'tEOSETH' and 'EOSETH' etc as symbol, but nothing I do whatsoever gives any results, rather I'm just receiving back empty arrays all the time (I can receive errors if I provide bogus symbols, but when I get the symbols what appears 'right' I get nothing). Tried not passing anything / passing null for the timestamps, and also tried passing timestamps, but also nothing seems to help there ...

**Comment by spig0t** [comment]
Also note - I now tried using CCXT instead, and with this, I do receive this latest order when I call fetchClosedOrders (and I also aren't required to provide the symbols when calling this, which is rather nice).

**Comment by ladanovn** [comment]
> @masterkain historical data requests are limited internally via the API at the moment, as we're in the process of implementing a new data archive/query system. With the growth in new users & trading activity, too many people requesting their lifetime histories via the API in an automated fashion could overload the system. Also w/ the recent DDoS attacks, etc.
> 
> So there's no way around it at the moment, except for using the Reports page. This will be fixed soon.


Question about requests for historical data through the API is still open?
I'm trying to use the accountTrades method, but it returns an empty array.

**Comment by enriquepiatti** [comment]
Same problem here V2 rest api orderHistory is returning empty array, always

**Comment by kebian** [comment]
Still an issue in February 2021

**Comment by ksamborski** [comment]
Could you please reopen this ticket? `order/hist` returns empty list no matter what parameters are passed.
