### ISSUE TITLE
Returned volume could be wrong

### ISSUE THREAD

**Issue by puppeteer701** [bitfinexcom/bitfinex-api-node#201]
Daily volume returned by library:
```
BTCUSD: 43440.60
ETHUSD: 193663.38
XRPUSD: 87789094.13
```

Daily volume on bitfinex statistics:
```
BTC/USD | 44,092.42
ETH/USD | 191,635.32
XRP/USD | 89,383,307.89
```

Am I reading something wrong here or has https://www.bitfinex.com/stats a higher refresh rate then ws of the library?

**Comment by f3rno** [comment]
@puppeteer701 ETH/USD in your example is actually less on the UI's side. They are two separate pathways to the same data, with two different caching behaviors.

The websocket feed should be preferred, and not cross-referenced with other sources (specifically REST,) as the access patterns & therefore caching differ.
