### ISSUE TITLE
Explanation on the submit order example 

### ISSUE THREAD

**Issue by soliveira-vouga** [bitfinexcom/bitfinex-api-node#202]
Hi, I'm having trouble understanding what sort of data I'm expecting from the submit order example below:

```javascript
const o = new Order({
    cid: Date.now(),
    symbol: 'tBTCUSD',
    price: 589.10,
    amount: -0.02,
    type: Order.type.EXCHANGE_LIMIT
  }, ws)

  let closed = false

  // Enable automatic updates
  o.registerListeners()

  o.on('update', () => {
    debug('order updated: %j', o.serialize())
  })

  o.on('close', () => {
    debug('order closed: %s', o.status)
    closed = true
  })

  debug('submitting order %d', o.cid)

  o.submit().then(() => {
    debug('got submit confirmation for order %d [%d]', o.cid, o.id)

    // wait a bit...
    setTimeout(() => {
      if (closed) return

      debug('canceling...')

      o.cancel().then(() => {
        debug('got cancel confirmation for order %d', o.cid)
      }).catch((err) => {
        debug('error cancelling order: %j', err)
      })
    }, 2000)
  }).catch((err) => {
    console.log(err)
})
```

What's the flow here. If I do an EXCHANGE MARKET order will there be an 'update' message sent? What sort of data is provided in the update message of an order? Why does the example have a setTimeout for 2 seconds and cancel the order if it is not closed? Is that just an example of dealing with an order that takes more than 2 seconds to fulfill? 

Also what exactly is the point of `o.registerListeners()`, is it necessary to call that method in order to receive update/close messages?

Thanks

**Comment by motocarota** [comment]
> What's the flow here.  If I do an EXCHANGE MARKET order will there be an 'update' message sent? 

Correct, that would be the platform informing you your order has been accepted.

> What sort of data is provided in the update message of an order?

Same as shown here https://github.com/bitfinexcom/bitfinex-api-node/blob/master/doc/ws2.md#WSv2+onOrderUpdate

> Why does the example have a setTimeout for 2 seconds and cancel the order if it is not closed? Is that just an example of dealing with an order that takes more than 2 seconds to fulfill?

That's just an example of an order with a lifespan of two seconds, it means that if the order does not get executed in two seconds it will be cancelled.

It doesn't make much sense probably, but I suppose it's just to show you how to cancel an order.

> Also what exactly is the point of o.registerListeners(), is it necessary to call that method in order to receive update/close messages?

Correct, this enable you to listen for order events (like 'update', 'close', 'cancel', ...)

**Comment by soliveira-vouga** [comment]
Thanks, that helps
