### ISSUE TITLE
Error for Websocket: Object.values is not a function in transports/ws2.js

### ISSUE THREAD

**Issue by droconnel22** [bitfinexcom/bitfinex-api-node#205]
// within an es6 class....
 this._bitfinexWS = new BFX().ws(2);  `        

this._bitfinexWS.on('open', () => {
           
            this._bitfinexWS.subscribeTrades(currencyPair);  
            this._bitfinexWS.onTradeUpdate({ pair: currencyPair }, (trades) => {  
                console.log(trades);
                if(trades) {
                    callback(trades);
                }            
            }); 
        });
        
        this._bitfinexWS.open();

`
Using v2.0.0-beta.

Please help, thanks!

**Comment by droconnel22** [comment]
Please let me know if you might need more information.

Thanks

**Comment by michaeljmonte** [comment]
I just ran into this, what version of Node.js are you running?

**Comment by f3rno** [comment]
@droconnel22 are you still seeing this?
@michaeljmonte can you provide more details? Is the error coming from the bfx lib?

**Comment by michaeljmonte** [comment]
I have since resolved it by upgrading my node.js. I was running 6.8 for some reason now I am running 9.5.

Yes the issue was coming from ws2.js in _propagateMessageToListeners.

`const listenerGroups = Object.values(this._listeners)`  

It seems older versions of Node.js (<7.0.0) do not support Object.values.

**Comment by f3rno** [comment]
@michaeljmonte hmm, good point. I've bumped the min node version to 7 here: https://github.com/bitfinexcom/bitfinex-api-node/pull/226/commits/7b6027b90bd28a61feca1452f2e80346cb2c8423

This is a case where it would have made sense to refactor the `Object.values` call out, but <6 is really quite old at this point, when 8.9.4 is available as LTS, and 9.5.0 is out.

I'm closing this for now, thanks for the heads up!

**Comment by droconnel22** [comment]
It was the Node version. Thank you!! I was running stable v 6.7. Will upgrade.
