### ISSUE TITLE
.onWalletSnapshot or .onWalletUpdate BALANCE_AVAILABLE always null

### ISSUE THREAD

**Issue by skylinezum** [bitfinexcom/bitfinex-api-node#212]
I think this is a bitfinex backend problem, but in my funding wallet balance_available always returns null for me. Even when a funding offer is provided to someone else.

**Comment by dubrovsky-kiril** [comment]
I think you need to send 'calc' message in order to receive updates. See "Important" section in 'Wallets'. https://docs.bitfinex.com/v2/reference#ws-auth-wallets

**Comment by dubrovsky-kiril** [comment]
Btw, I am switching to second version of package and I got small issue with calling . onWalletSnapshot. What are the request params? What {opts} should be used if I want to fetch 'EXCHANGE' wallet snapshot?

**Comment by f3rno** [comment]
@dubrovsky-kiril correct :) Thanks for answering!
