### ISSUE TITLE
REST API v2 Positions  last four fields are "null" !

### ISSUE THREAD

**Issue by hems** [bitfinexcom/bitfinex-api-node#214]
According to finex documentation: https://docs.bitfinex.com/v2/reference#rest-auth-positions he last four items on the Array would be PL / PL_PERC / PRICE_LIQ and LEVERAGE but i get NULL instead.

As in: ["tBTCUSD","ACTIVE",-0.01,7757.90153256,-0.00020637,0,null,null,null,null]

This seems to be an error on the server side, is anybody having the same issue?

Does REST V1 /positions end point work as expected? I'll give it a try asap..

**Comment by jgordor** [comment]
Hi @hems same to me, do you find any solution?

**Comment by hems** [comment]
@jgordor sent an email to finex support about a week and still waiting, so far the closest to a solution i got was [playing this video in loop](https://www.youtube.com/watch?v=_O1hM-k3aUY)

Will report back once I hear from them, i'm sure this will be a easy fix.

**Comment by f3rno** [comment]
@jgordor @hems this is a backend issue and a fix is in the works, I'll update you guys when it's out.

**Comment by hems** [comment]
nice one @f3rno , thank you

**Comment by jgordor** [comment]
Hi @f3rno any news on this? Thanks

**Comment by f3rno** [comment]
@hems @jgordor this has been fixed on the backend, apologies for the late response.
