### ISSUE TITLE
Query options are not supported for REST api

### ISSUE THREAD

**Issue by ThePlenkov** [bitfinexcom/bitfinex-api-node#215]
Dear devs,

For REST API's like https://docs.bitfinex.com/v2/reference#rest-public-candles

there are query options defined

However this API doesn't support them.

For example to simulate candles I need to read them from the past and in this case I have to call internal `_makePublicRequest` with URL created manually.

May be it makes sense to add just oParams for each method and to process them with the function like this:

```js
makeUrl(sPath, oParams) {
        let query = oParams ? "?" + new URLSearchParams(oParams).toString() : "";
        return sPath + query;
    }
```

What do you think?
Thanks!

**Comment by f3rno** [comment]
Fixed in `master`
