### ISSUE TITLE
Api that gets list of crypto pairs available for trades

### ISSUE THREAD

**Issue by dubrovsky-kiril** [bitfinexcom/bitfinex-api-node#216]
Hello. I want to say thanks for the library. It ease my life 👍 

I just started to look in the api and I didnt find one that can get me list of supportable crypto pairs on Bitfinex. Is there one? Or otherwise could you please implement it? Would be reaaallyy helpful! :)

**Comment by f3rno** [comment]
@dubrovsky-kiril check out https://github.com/bitfinexcom/bitfinex-api-node/blob/master/examples/rest2/symbols.js
