### ISSUE TITLE
apikey: invalid error

### ISSUE THREAD

**Issue by ttbarnes** [bitfinexcom/bitfinex-api-node#217]
Hiya, i'm trying to get some trades/history data with v2 api. With either`bitfinex-api-node` module or `request-promise`, i'm getting this error response: `["error",10100,"apikey: invalid"]`

I've looked through documentation and other issues like #80, I always seem to get this error regardless. Am I missing something, or maybe something missing in the docs?

Example:

```
import rp from 'request-promise';

const KEY = 'asdf';
const SECRET = 'ghjk';
const BITFINEX_BASE_URL = 'https://api.bitfinex.com';
const BITFINEX_TRADES = '/v2/auth/r/trades/hist';

const nonce = Date.now().toString();
const completeURL = BITFINEX_BASE_URL + BITFINEX_TRADES;
const body = {
  request: BITFINEX_TRADES,
  nonce
};

const payload = new Buffer(JSON.stringify(body))
  .toString('base64');

const signature = crypto
  .createHmac('sha384', querySecret)
  .update(payload)
  .digest('hex');

const options = {
  url: completeURL,
  headers: {
    'X-BFX-APIKEY': queryKey,
    'X-BFX-PAYLOAD': payload,
    'X-BFX-SIGNATURE': signature
  },
  body: JSON.stringify(body),
  method: 'POST'
};

rp(BITFINEX_BASE_URL + BITFINEX_TRADES, options, (error, response, body) => {
  console.log('body ', body); // ["error",10100,"apikey: invalid"]
});

```

I've tried adding fresh API keys and get the same issue.

**Comment by f3rno** [comment]
@ttbarnes if you still need help with this, `queryKey` and `querySecret` need to be renamed to `KEY` and `SECRET` respectively.

**Comment by ttbarnes** [comment]
@f3rno updated - sorry that was a copy/paste error.

I'm still getting this issue. Any ideas/help appreciated!

**Comment by f3rno** [comment]
@ttbarnes hmm, well, your RESTv2 key/sig headers are invalid, this is from the `RESTv2` class:

```js
    const url = `${this._url}/v2${path}`
    const n = nonce()
    const sigPayload = `/api/v2${path}${n}${JSON.stringify(payload)}`
    const { sig } = genAuthSig(this._apiSecret, sigPayload)

    return rp({
      url,
      method: 'POST',
      headers: {
        'bfx-nonce': n,
        'bfx-apikey': this._apiKey,
        'bfx-signature': sig
      },
      agent: this._agent,
      body: payload,
      json: true
    })
```
Can you try to use `RESTv2` from the latest `master` branch for this instead? This method should work:
```js
  /**
   * @param {string} symbol
   * @param {number} start
   * @param {number} end
   * @param {number} limit
   * @param {Method} cb
   * @return {Promise} p
   * @see https://docs.bitfinex.com/v2/reference#rest-auth-trades-hist
   */
  trades (symbol = 'tBTCUSD', start = null, end = null, limit = null, cb) {
    return this._makeAuthRequest(`/auth/r/trades/${symbol}/hist`, {
      start, end, limit
    }, cb, Trade)
  }
```

Setup via:

```
const bfx = new BFX({
  apiKey: API_KEY,
  apiSecret: API_SECRET,
})

const rest = bfx.rest(2)

rest.trades(...
```

**Comment by ttbarnes** [comment]
@f3rno thank you, all working with this approach 😄 However I'm a bit confused with the trades endpoint, i'm always getting a `null []` response, with seemingly any trade pair, EG 

`const opts = { symbol: 'tIOTBTC' }`
`const opts = { symbol: 'tIOTUSD' }`

There are definitely trades in my account for these pairs.

Calling like this with `RESTv2` from latest version:

`rest.trades(opts.symbol, (err, data) => ...`

I can't see anything in the documentation regarding this, any ideas? I appreciate StackOverflow maybe a better place for this issue.

**Comment by f3rno** [comment]
@ttbarnes the `start`, `end`, and `limit` args are not optional on the `rest.trades()` call. This is because the cb is optional, so you can do `rest.trades(opts.symbol).then((trades) => { ... }).catch((err) => ...`

Can you try that to see if it gives a different result?

**Comment by ttbarnes** [comment]
@f3rno i'm getting a successful response with this approach, but with an empty array.

**Comment by tgmTimsah** [comment]
Bitfinex V2 api for
payload:

"/api/v2/auth/w/order/submit1579850962955{"amount":"0.0008","price":"8500","symbol":"tBTCUSD","type":"LIMIT"}"

I get an error for this load, what is not true , thanks.

**Comment by f3rno** [comment]
@tgmTimsah please open a new issue in the future, as this is unrelated.

Are those parameters in the URL or is it a copy/paste artifact? The params need to be passed in the request body, see the docs: https://docs.bitfinex.com/reference#rest-auth-submit-order

**Comment by sawrubgupta** [comment]
const apiKey = '' // const apiKey = 'paste key here'
    const apiSecret = '' // const apiSecret = 'paste secret here'
    
    const apiPath = 'v2/auth/w/deposit/address'// Example path
    
    const nonce = (Date.now() * 1000).toString() // Standard nonce generator. Timestamp * 1000
    const body = {
    } // Field you may change depending on endpoint
    
    let signature = `${apiPath}${nonce}${JSON.stringify(body)}` 
    // Consists of the complete url, nonce, and request body
    
    const sig = CryptoJS.HmacSHA384(signature, apiSecret).toString() 
    // The authentication signature is hashed using the private key
    
    fetch(`https://api.bitfinex.com/${apiPath}`, {
      method: 'POST',
      body: JSON.stringify( {
         method: 'LNX', wallet: 'exchange' 
      }),
      headers: {
        'Content-Type': 'application/json',
        'bfx-nonce': nonce,
        'bfx-apikey': apiKey,
        'bfx-signature': sig
      }
    })
    .then( async(res) => {
     const response = await res.json();
      console.log(response);
      
    })//Logs the response body
    .catch(err => {
        console.log(err)
     })
})

anybody know what wrong, I am doing here ?

**Comment by f-dg** [comment]
`apikey: invalid error` tells you that your signature is not correct.
Usually, it is due to using wrong hashing functionality, there are the whole family of hashing functions and versions, you need to choose the right one otherwise API doesn't allow you to get in.
For example, in case with rust there are `sha`, `sha2` and `sha3` libs and each one has sha384. Bitfinex API expects you to use `sha2_384`. 

`openssl list -digest-algorithms` shows how many SHA*  exist.

[sawrubgupta](https://github.com/sawrubgupta) It seems that you forget to add  `/api` to `let signature = ${apiPath}${nonce}${JSON.stringify(body)}`  with
