### ISSUE TITLE
Request params for submit order via WS2

### ISSUE THREAD

**Issue by dubrovsky-kiril** [bitfinexcom/bitfinex-api-node#219]
Hello. Could someone explain me please how to make new orders. I am using library version v1.2.1. I didn't find any description except code example below:

```js
function submitOrder () {
  const payload = [
    0,
    'on',
    null,
    {
      'gid': 1,
      'cid': cId, // unique client order id
      'type': 'LIMIT',
      'symbol': 'tBTCUSD',
      'amount': '1.0',
      'price': '200',
      'hidden': 0
    }
  ]

  bws.send(payload)
}
```

Questions:
1. What are first three params in payload variable? What do they mean?
2. What are 'gid' and 'hidden' props in 4th param?

**Comment by f3rno** [comment]
@dubrovsky-kiril have a look at the example: https://github.com/bitfinexcom/bitfinex-api-node/blob/master/examples/ws2/orders.js

You don't need to build the payload yourself, you can instantiate a new order and submit it. `gid` is a group ID which binds orders together ('Cancel Group' in the UI), and hidden is the hidden flag :)

I'm closing this now, but let me know if you have other questions.
