### ISSUE TITLE
False "not enough balance" error

### ISSUE THREAD

**Issue by dubrovsky-kiril** [bitfinexcom/bitfinex-api-node#220]
Hi. I am trying to execute new order, but as a response I get error with message below:
'Invalid order: not enough tradable balance for 1.0 IOTETH at 0.002107'

But it is not true. I have enough of balance. Why this is happening? Below is trade execution code:
  bitfinexWS.send([0, 'on', null, {
    "gid": 1,
    "cid": Date.now(),
    "type": "LIMIT",
    "symbol": "tIOTETH",
    "amount": "1",
    "price": "0.002107",
    "hidden": 0
  }])

**Comment by Valdineyap** [comment]
Hello,

  Did you find a solution for this?
  I have the same problem!

Thanks in advance,

**Comment by soliveira-vouga** [comment]
I got this error as well just today. I sent an order with type "MARKET". There was plenty of balance for the order but still got the following error:

`ERROR: Invalid order: not enough tradable balance for 50.0 XRPUSD at 0.76735`

**Comment by Valdineyap** [comment]
I found the problem: When defining the "TYPE" parameter you must use "exchange market" and "exchange limit" intead of only "market" and "limit". 
When you don't have the word "exchange" the transactions are related to some of the other two Wallets (Marging or Funding)
