### ISSUE TITLE
RESTv2 Symbols/Symbol Details Endpoint

### ISSUE THREAD

**Issue by f3rno** [bitfinexcom/bitfinex-api-node#224]
As per https://github.com/bitfinexcom/bitfinex-api-node/pull/196

The `RESTv2` wrapper needs to provide a way to fetch the full active symbol set, and then pass those symbols directly to the other API methods. This requires a new endpoint on the v2 REST API.

**Comment by masterkain** [comment]
I'd love also the get the currency symbol we can find the CSV exports, sometimes it's different and can't be derived. `tQSHBTC` => `QASH` (in CSV) => `QSH:BTC` (permalink)

the best would be also to specify the CMC permalinks such as `qash`, `streamr-datacoin` to better identify the currencies and permit enumeration, but that's perhaps asking too much.

**Comment by f3rno** [comment]
Alright, for the moment we are providing a `RESTv1` pass-through on `RESTv2` with the methods available as `rest.symbols()` and `rest.symbolDetails()`, code here: https://github.com/bitfinexcom/bitfinex-api-node/blob/master/lib/transports/rest2.js#L601

In the future we will provide dedicated endpoints for the v2 REST API, but I am closing this issue as this is not pertinent to the node library :slightly_smiling_face:
