### ISSUE TITLE
Restv2 private trades always return empty array

### ISSUE THREAD

**Issue by masterkain** [bitfinexcom/bitfinex-api-node#229]
might be a server-side issue, got the same results in ruby (custom lib, not `bitfinex-api-rb` (https://github.com/bitfinexcom/bitfinex-api-rb/issues/65)

anyone else with the same issue?

**Comment by f3rno** [comment]
@masterkain can you provide more details? I can't replicate, `bitfinex-api-node` trades work fine on my end.

**Comment by masterkain** [comment]
hello, at the moment in js I have (includes different stuff I tried) this test script, either my account is broken or I don't know, v1 works fine but I cannot tell a margin trade from an exchange one in that case.

```
const RESTv2 = require("bitfinex-api-node").RESTv2
const {
  Trade
} = require('bitfinex-api-node/lib/models')

const Restv2 = new RESTv2({
  apiKey: 'xxx', // replace
  apiSecret: 'xxx' // replace
});


const _start = undefined; // 1504642790000; // Date.now() - (90 * 24 * 60 * 60 * 1000)
const _end = undefined; //1504815590000; Date.now();
const _limit = undefined;

Restv2.trades('tETHBTC', _start, _end, _limit, function() {
  console.info("In CB", arguments);
  console.info("------")
}).then( function() {
  console.info("Then", arguments);
  console.info("=====");
}, function() {
  console.warn("Catch", arguments);
});
```

empty array as result, I have some ruby code that no matter what parameters I try, it's always [].
I can provide my credentials in pvt if you'd like to test it out.

**Comment by masterkain** [comment]
I got it working again in my ruby version, I don't understand yet what I'm doing wrong, but we can close this I guess, sorry for the noise.

**Comment by BarnumD** [comment]
I'm also getting an empty array for private trades.  Would prefer this to be re-opened.
