### ISSUE TITLE
Difference between 'ou' and 'tu' events

### ISSUE THREAD

**Issue by dubrovsky-kiril** [bitfinexcom/bitfinex-api-node#234]
Hello. I got small question regarding difference between 'ou' and 'tu' events. Could someone make it clear for me? Don't they both stand for order update?

**Comment by f3rno** [comment]
@dubrovsky-kiril `order update` & `trade update` respectively.

**Comment by dubrovsky-kiril** [comment]
what means trade update? Isn't 'order update === trade update'?

**Comment by f3rno** [comment]
@dubrovsky-kiril no since they are two separate events; check the docs: https://docs.bitfinex.com/v2/reference#ws-auth-trades and https://docs.bitfinex.com/v2/reference#ws-auth-orders

A trade is essentially an executed order (afaik)

**Comment by dubrovsky-kiril** [comment]
Hm... Thanks. I will!

**Comment by dubrovsky-kiril** [comment]
Small additional question. If my order got executed partially. How can I track this? What event should I use?
