### ISSUE TITLE
Websocket model Tick.js missing? 

### ISSUE THREAD

**Issue by nixxle** [bitfinexcom/bitfinex-api-node#237]
The unserializing of Websocket Ticks doesn't work for me. 

`bitfinex-api-node\lib\transports\ws2.js:541`
`      data = Tick.unserialize(msg[1])`
`TypeError: Cannot read property 'unserialize' of undefined`

**Comment by f3rno** [comment]
@nixxle Can you try this again with the latest `master`? We recently merged some PRs in which changed this logic.

**Comment by nixxle** [comment]
I tried todays master branche. Same error. 

If you look in ws2.js on line #27 it says Tick which should come from /models/index.js 

If you look in models/index.js there is no Tick export.

**Comment by nixxle** [comment]
I have now tried 2..0.0-beta.1 

Tick.js is back. Which is nice. 

The data that comes from the server for a tBTCEUR tick: 

`[1,[9033.3,44.68155408,9035.8,51.238849,-112.8,-0.0123,9032.6,1110.94672631,9355.4,8970.1]]`

then, in ws2.js::532

`_handleTickerMessage (msg, chanData) {`

the raw data is supposed to go to Tick.unserialize() 

`const data = this._transform ? Tick.unserialize(msg[2]) : msg[2]` 

However, there is no msg[**2**] the data from the server does not match what is expected by Tick.unserialze
