### ISSUE TITLE
State-of-the-art New Order-Placement

### ISSUE THREAD

**Issue by s5m4** [bitfinexcom/bitfinex-api-node#238]
Hi all, 

**how do you place your new orders?** 

I am really wondering because there are some options for it but none seems to be working, which confuses me a bit:
a) websocket connection currently seems unstable. (see issues #233 and #138) 
the example given in the readme doc ("create and track order") uses websocket which is not a good solution when websocket connections silently crash without a possibility to reset them. 
b) the current RESTv2 does not include a new_order-function (like V1 used to have). or is placing order with it too obvious to put it in the docs? 
c) RESTv1(which had a cool looking new_order() function) seems to be deleted from the project. The constructor from the wiki is throwing an error:  
```
Error: constructor takes an object since version 2.0.0, see:
https://github.com/bitfinexcom/bitfinex-api-node#version-200-breaking-changes
```
thanks for your help.

**Comment by f3rno** [comment]
@s5m4 the ws2 API is preferred, and the instability is being addressed :)
