### ISSUE TITLE
ws api order lifecycle questions

### ISSUE THREAD

**Issue by machard** [bitfinexcom/bitfinex-api-node#239]
Hello,

Here is a log of the websocket stream i use to pass and monitor orders:

```
source:bitfinex:ws:fixBTCEUR0 send [ 0,
    'on',
    null,
    { type: 'EXCHANGE LIMIT',
      amount: { [String: '0.01'] _int: [Object], _precision: 2, _nan: undefined },
      price: { [String: '7788.6'] _int: [Object], _precision: 1, _nan: undefined },
      flag: 0,
      symbol: 'tBTCEUR',
      cid: 1 } ] +334ms

source:bitfinex:ws:fixBTCEUR0 send [ 0,
    'on',
    null,
    { type: 'EXCHANGE LIMIT',
      amount: { [String: '0.01'] _int: [Object], _precision: 2, _nan: undefined },
      price: { [String: '7741.8'] _int: [Object], _precision: 1, _nan: undefined },
      flag: 4096,
      symbol: 'tBTCEUR',
      cid: 2 } ] +8ms

source:bitfinex:ws:fixBTCEUR0 write [ 0,
    'oc',
    [ 8765161516,
      null,
      1,
      'tBTCEUR',
      1519641862430,
      1519641862486,
      0,
      0.01,
      'EXCHANGE LIMIT',
      null,
      null,
      null,
      0,
      'EXECUTED @ 7786.5188(0.01)',
      null,
      null,
      7788.6,
      7786.5187878,
      null,
      null,
      null,
      null,
      null,
      0,
      0,
      0,
      null,
      null,
      null,
      null,
      null,
      null ] ] +544ms

source:bitfinex:ws:fixBTCEUR0 write [ 0,
    'on',
    [ 8765161517,
      null,
      2,
      'tBTCEUR',
      1519641862430,
      1519641862486,
      0.01,
      0.01,
      'EXCHANGE LIMIT',
      null,
      null,
      null,
      0,
      'ACTIVE',
      null,
      null,
      7741.8,
      0,
      null,
      null,
      null,
      null,
      null,
      0,
      0,
      0,
      null,
      null,
      null,
      null,
      null,
      null ] ] +0ms

source:bitfinex:ws:fixBTCEUR0 write [ 0,
    'te',
    [ 203049719,
      'tBTCEUR',
      1519641862456,
      8765161516,
      0.01,
      7786.5187878,
      null,
      null,
      -1 ] ] +204ms

source:bitfinex:ws:fixBTCEUR0 write [ 0,
    'tu',
    [ 203049719,
      'tBTCEUR',
      1519641862456,
      8765161516,
      0.01,
      7786.5187878,
      'EXCHANGE LIMIT',
      7788.6,
      -1,
      -0.1635043,
      'USD' ] ] +0ms
```

So as you can see I pass one limit buy order below the current price (the cid 2) and one that will take liquidity (the cid 1). The behaviors I need clarification with are related to the fact that i receive "oc" without prior "on" and also the "te" comes after the "oc" for the order with cid1..

- It means in my "oc" handler I need to take into account that i may not have received all the "te" events or even the initial "on" event ?
- should I use the "ou" or "te" event to track partial fills ? which one is faster ? would "ou" events happen always before the "oc" event ?
- what would be the sequence of events if i post a limit order of 0.2, of which 0.1 are directly "taken" leaving 0.1 to rest on the order book ?

I would appreciate any insight here thank you.

Thx

**Comment by f3rno** [comment]
@machard I've broken up my points below:

 * Yes, it is possible to receive an `oc` packet without an initial `on`/`ou` if the order fills immediately.
 * For partial fills either `on` or `ou` may be emitted; `on` comes first if a partial fill occurs immediately
 * `te` cannot be relied upon to arrive before the matching `ou`/`oc` packet. From my own logs, `ou` arrives first.
 * For the 0.2 order, an `on` packet would arrive first with a status of `PARTIALLY FILLED: ...`, followed by a `te`/`tu` pair

Let me know if this makes sense, and matches your tests.

**Comment by machard** [comment]
OK thank you, this makes sense.
Last question:
A limit buy of 0.2 btc goes in the order book then gets filled 0.1 and then get filled again 0.1, what will be the sequence : "on", "ou", "ou", "oc" or "on", "ou", "oc" ?

**Comment by f3rno** [comment]
@machard it should be first an `on` for entry into the OB, followed by an `ou` w/ `PARTIA...` status,   followed by an `oc` with a status along the lines of: `EXECUTED; was PARTIALLY FI...` :slightly_smiling_face: 

Shorter: `on`, `ou`, `oc`

**Comment by machard** [comment]
ok thx, i'm all good now. you can close

**Comment by f3rno** [comment]
Alright, feel free to re-open if you need any more info o/
