### ISSUE TITLE
auth channel, get notifications when filtering

### ISSUE THREAD

**Issue by machard** [bitfinexcom/bitfinex-api-node#241]
Hey,
About ws2 auth channel.
If i use `filter: ['trading']` i loose the notifications, is there a way to only get trading and notifications messages or my only choice is to go with the full channel ?
Thx

**Comment by f3rno** [comment]
How are you applying that filter?

**Comment by machard** [comment]
@f3rno 
from here https://docs.bitfinex.com/v2/docs/ws-auth#section-channel-filters

**Comment by f3rno** [comment]
@machard this is technically available via the `notify` filter, but it wasn't documented. The official docs have been updated: https://docs.bitfinex.com/v2/docs/ws-auth#section-channel-filters
