### ISSUE TITLE
Add FAQ: Order Rate Limit

### ISSUE THREAD

**Issue by machard** [bitfinexcom/bitfinex-api-node#242]
Hey,

Can I know exactly what is the maximum number of orders per 10 minutes ?
Is this limitation per pair ?
Is this limitation per api key ?
Is this limitation per websocket connexion ?
What is the logic behind this limitation ?

Thx

**Comment by f3rno** [comment]
@machard this has changed recently; the base limit is 1000 orders per 5 minutes per user, and increases proportionally with your trading volume. I'll add a FAQ entry to the readme.

**Comment by machard** [comment]
👍

**Comment by ksergey** [comment]
@f3rno 

Could you please clarify:
If I reach the limit, I receive rejects or something like that for new order?

Thanks

**Comment by jtfarks** [comment]
I'm seeing the message: 'Reached Maximum number of orders per 10 minutes'. Do you mean this has changed to 5mins now for the websocket or am i hitting the next level of throttling?
