### ISSUE TITLE
Raw Orderbook Messages Logic

### ISSUE THREAD

**Issue by archienorman11** [bitfinexcom/bitfinex-api-node#245]
Hi, 

Wondering if someone could help me understand a couple of things with the bfx websocket api v2 `raw orderbook messages`:

1: `when PRICE = 0 then you have to delete the order` - does this only mean that an order has been cancelled? Or are they other reasons why the order might be deleted, for example, a market or limit order also result in this message being sent? If so, can I match a trade (from trade channel) with that of these messages where the `price = 0`, as far as I can see, `trade_id` has no correlation to `order_id`.

2: `when PRICE > 0 then you have to add or update the order` - does this mean, if the price is not 0 and the order does not exist, then add it, otherwise overwrite the order values on the book with the new values in the message just received?  

Any help hugely appreciated. 

Thanks,

**Comment by f3rno** [comment]
@archienorman11 

1: It means the order has been removed from the OB, either due to cancellation or execution. You should be able to identify the trade that caused this by the `ORDER_ID` field on the `te/tu` packets.

2: Yes, exactly :)

Please close this issue if that makes sense
