### ISSUE TITLE
Missing FAQ: WS2 sequences

### ISSUE THREAD

**Issue by ksergey** [bitfinexcom/bitfinex-api-node#246]
Hi Devs!

Could you please clarify the purpose of sequences (SEQ_ALL) on ws2 transport?
Sequence always starts from 1 and monotonically increases. It looks like set by a frontend (not by matching engine/exchange core).

Thanks

**Comment by f3rno** [comment]
@ksergey it enables you to verify that no packets have been dropped; if a sequence number is skipped, it means a packet was lost somewhere. This can also occur if an action was initiated via the UI, and is being addressed in https://github.com/bitfinexcom/bitfinex-api-node/issues/193 (fix pending, max ~1wk)

**Comment by ksergey** [comment]
@f3rno Where packet can be lost?
