### ISSUE TITLE
Synchronize orders state after websocket reconnect

### ISSUE THREAD

**Issue by ksergey** [bitfinexcom/bitfinex-api-node#247]
Hello!

I have a problem with synchronization orders state after websocket reconnected. 
After websocket reconnection I need to know what happend with order. There is could be few cases:
1. Order stayed AS-IS
2. Order filled
3. Order canceled
4. Order placed

I know about `os` message, but it's not enought for synchronize orders state.

Questions:
1. Is it possible to receive trade history for an order via WS2?
2. Is it possible to receive order state for a filled/canceled order via WS2?
3. What I can do with new orders in case of reconnect (i.e. new order request was sent, but `n` or `on/oc/ou` message was not received before reconnect)? I known I can found pending new order in `os` message but it particular case (order could be not placed, canceled, or filled after reconnect)
4. Looks like WS and REST interfaces unsynchronized. I received empty array in response for `Order Trades` (https://docs.bitfinex.com/v2/reference#rest-auth-order-trades), but I know trades exists for requested order. It's a bug?

Thanks

**Comment by f3rno** [comment]
@ksergey hmm, this is not so straightforward.

1. As WS2 is primarily a push-feed, at the moment it is not possible.
2. If connected when the packet comes through, yes, but it is not possible to query the state of a specific historical order via WS2. For this, REST2 should be used. (see #4)
3. Currently nothing, but I will bring this up internally & see what we can do.
4. Ditto, see #3. It is not a bug, the APIs are out of sync (WS2 is real-time, REST2 is buffered)

I will update this issue as per #3 & #4

**Comment by ksergey** [comment]
@f3rno 

4. How long need to wait before trade will be visible via REST2?

More questions:
5. Sometimes I got disconnect right after receiving `on-req` notification. But the order from notification missed in `os` message after reconnect. It's bug or feature? 
6. Sometimes my application sent `Order Multi-OP` (i.e. 5-7 order new or 5-7 order cancel requests) and not received any response via WS2. But in UI I see orders placed or canceled. It's looks like a bug. What you can recommend to do in case like that?

Thanks

**Comment by f3rno** [comment]
@ksergey I'm closing this as it's an old issue, and mainly applies to concepts on the backend. I'm cleaning up issues now before releasing a complete rewrite of this repo (split into modules), hence the mass-close of old/out of scope issues.

However, if you ever again see dropped notifications on ws2 (the last mention being at end of Feb from you), please open a new issue for it, as that is definitely a bug.
