### ISSUE TITLE
ERROR: Must specify a 'request' field in the payload that matches the URL path

### ISSUE THREAD

**Issue by burzakovskiy** [bitfinexcom/bitfinex-api-node#25]
I'm receiving an error on POST request.

**Comment by dutu** [comment]
This error seems to occur for newly released v1.0.0 as well.
Can be reproduced by calling method `active_orders`.

Can we please have it fixed.

**Comment by dutu** [comment]
Should be fixed with PR https://github.com/bitfinexcom/bitfinex-api-node/pull/66 and https://github.com/bitfinexcom/bitfinex-api-node/pull/67

**Comment by robertkowalski** [comment]
thank you, reviewing now

**Comment by dutu** [comment]
thanks, pls also publish the new version on NPM, when ready

**Comment by robertkowalski** [comment]
fixed in b90221a2002e2297c6dbbcd9f8dc42f3ca6f2489
