### ISSUE TITLE
Trades via ws return undefined values

### ISSUE THREAD

**Issue by mescalina** [bitfinexcom/bitfinex-api-node#256]
The structure of the trades object has changed and in order to work this modification is needed:

EDIT ws2.js inside bitfinex-api-node/lib/transports:

```
 _handleTradeMessage (msg, chanData) {
    //const eventName = msg.length === 3 ? msg[1] : 'trades' 
    const eventName = msg.length === 4 ? msg[1] : 'trades'
    //let payload = msg[msg.length - 1]
    let payload = msg[msg.length - 2]
```

I don't know if something else is affected by this change of the Bitfinex api

**Comment by datgrog** [comment]
Thanks man, I was trying to play with  [ws2-example-subscribe-to-trades-by-pair](https://github.com/bitfinexcom/bitfinex-api-node#ws2-example-subscribe-to-trades-by-pair) but it shows void things like 

```
[0]
[1]
[2]
[3]
[4]
[5]
[6]
```

but now it works, much better.

```
[ 211028540, 1520974237525, -0.1, 9088.7 ],
[ 211028533, 1520974233413, 0.00025, 9080.9 ],
[ 211028528, 1520974233112, 0.989, 9080.9 ],
[ 211028525, 1520974230952, 0.01075, 9080.9 ],
[ 211028517, 1520974229091, 0.01, 9080.9 ],
[ 211028516, 1520974229090, -0.1, 9080.8 ],
[ 211028511, 1520974229021, -0.1, 9080.8 ]
```

Is this repo officially supported by bfx ?

**Comment by tomatopeel** [comment]
Wow this is horrible... Really Bitfinex?

**Comment by f3rno** [comment]
This is now fixed in `master`
