### ISSUE TITLE
OCO Example not working here

### ISSUE THREAD

**Issue by lucasleets** [bitfinexcom/bitfinex-api-node#257]
i tried this:

const o = new Order({
cid: Date.now(),
symbol: 'tSANUSD',
type: Order.type.EXCHANGE_LIMIT,
amount: -10,
oco: true,
price: 5,
priceAuxLimit: 1,
}, ws)

ERROR: price_oco_stop: invalid

Added price_oco_stop 1,

and get ERROR: price_oco_stop: invalid, again

How can i fix this?

**Comment by hems** [comment]
Same here, also happens with type=Order.type.LIMIT !

````
Error: ERROR: price_oco_stop: invalid
    at WSv2._onWSNotification (/Volumes/backpack/git/hemz/sozo/action/node_modules/bitfinex-api-node/lib/transports/ws2.js:336:39)
....

**Comment by hems** [comment]
@f3rno I can see you wrote models/order.js and examples/ws2/oco-order.js maybe you know if something changed since then?

**Comment by shannon-murdoch-webjet** [comment]
Running into the same issue here. OCO orders are coming back with the error also.
ERROR: price_oco_stop: invalid

**Comment by cryptomius** [comment]
I'm not sure if it helps, but I found I needed two libraries installed to get this library working..
`npm install crc-32
npm install --save bignumber.js`

**Comment by hems** [comment]
@cryptomius have you managed to post OCO orders?

**Comment by cryptomius** [comment]
@hems yes I have - check out https://github.com/cryptomius/Bitfinex-Auto-Stop-121-Scale-Out/
