### ISSUE TITLE
False error on balance when submitting an order

### ISSUE THREAD

**Issue by soliveira-vouga** [bitfinexcom/bitfinex-api-node#262]
I recently submitted an order with type `MARKET` and I got the following error:

`ERROR: Invalid order: not enough tradable balance for 50.0 XRPUSD at 0.76735`

However, there is plenty of available balance to make this trade. This is the first time I've seen this issue. Any suggestions?

**Comment by ddeath** [comment]
This can happen if you recently made a trade and exchange did not have updated your balance yet.

**Comment by f3rno** [comment]
@ddeath correct :)
