### ISSUE TITLE
What's the difference between a "MARKET" order and an "EXCHANGE MARKET" order?

### ISSUE THREAD

**Issue by soliveira-vouga** [bitfinexcom/bitfinex-api-node#263]
I recently made a change to my trader to use Order.type.MARKET instead of Order.type.EXCHANGE_MARKET and upon the first trade I got the error mentioned here: https://github.com/bitfinexcom/bitfinex-api-node/issues/262

There was more than enough of balance to execute this trade. I'm not sure if it was a coincidence and I just happened to receive a false negative on this trade or if it's something related to the order type.

**Comment by gsampathkumar** [comment]
MARKET is margin trading
EXCHANGE MARKET is on the exchange with no margin.

**Comment by f3rno** [comment]
@gsampathkumar correct, thanks for the answer
