### ISSUE TITLE
Ticker

### ISSUE THREAD

**Issue by gguney** [bitfinexcom/bitfinex-api-node#264]
I've successfully run web socket but when I use the example :

        const SYMBOL = 'tIOTEUR'
        ws.on('open', () => {
            debug('open')
            ws.subscribeTicker(SYMBOL)
        })

        ws.onTicker({ symbol: SYMBOL }, (ticker) => {
            console.log('%s ticker: %j', SYMBOL, ticker);
        })
        ws.open();
Console outputs: 

tIOTEUR ticker: 1
tIOTEUR ticker: 2
tIOTEUR ticker: 5
tIOTEUR ticker: 11
tIOTEUR ticker: 15
tIOTEUR ticker: 19

Shouldn't this show the current ticker price? How can I get current ticker price?

**Comment by NemesisFLX** [comment]
Same problem here to.

**Comment by Lettro** [comment]
Thanks @NemesisFLX! That fixes the issue 🙌

**Comment by pelly-ryu** [comment]
is this a bug of the library?

**Comment by f3rno** [comment]
This is fixed in `master` now guys. @NemesisFLX thanks for taking care of it in the meantime!
