### ISSUE TITLE
Sockets return Error: unexpected server response (429)

### ISSUE THREAD

**Issue by JanMesaric** [bitfinexcom/bitfinex-api-node#266]
Hey,

I'm currently subscribed to tickets via subscribeTrades and orderbooks via subscribeOrderBook, for 15 pairs. I'm using bfx w2. I make one instance of BFX object and call open() on it once, after that a on() method triggers subscribing me to what was mentioned before.

I was under impression that sockets would not hit any API limitations, and it works fine, but after 30-60 minutes I start to randomly get 429 errors. 

Any ideas on how to avoid it?

**Comment by PerterPon** [comment]
So am I, this error shows up after about 5 hours later

**Comment by ddeath** [comment]
I am getting 429 too. Before bitfinex update it was fine. Maybe something changed on the server?

**Comment by f3rno** [comment]
Closing as this is outdated; we're adding in a 50 channel-per-socket limitation soon which will limit this problem in the future. It is possible to receive 429 from too many subscriptions/ws requests.
