### ISSUE TITLE
Error: ob update for unknown price level: [0.65581,0,-1]

### ISSUE THREAD

**Issue by ddeath** [bitfinexcom/bitfinex-api-node#269]
Hello Guys,

we recently started to get error:
Error: ob update for unknown price level: [0.65581,0,-1]

It started to pop up after Bitfinex exchange update. Any ideas how could we fix it?
Thank you

**Comment by f3rno** [comment]
@ddeath is this still happening?

**Comment by ddeath** [comment]
@f3rno yes it is. Last time I have seen this error was 2018-04-07.
