### ISSUE TITLE
Update/Amend order through WS2 API

### ISSUE THREAD

**Issue by nikolaykm** [bitfinexcom/bitfinex-api-node#271]
Hi guys,

Do you know if there is a way to update/amend order through the WS2 API. In the documentation there is only sections for creating/canceling orders. However updating order from the WebInterface is possible and when I update order from there I'm getting "ou-req" and then "ou" for that order. 

Do you know how I can achieve the same functionality through the APIs, without first canceling the order and then placing a new one?

**Comment by ksergey** [comment]
`ox_multi` ?

**Comment by nikolaykm** [comment]
"ox_multi" with "oc" and "on" in it is first cancelling the order and then creating a new one. 

That is better than sending the updates one by one, but its also generating a new order id. However it seems that updating order from the WebUI is possible without first canceling it and then creating a new one, so I'm wondering how this could be done using the API?
