### ISSUE TITLE
"StatusCodeError: 500 - undefined"

### ISSUE THREAD

**Issue by ddeath** [bitfinexcom/bitfinex-api-node#275]
When I did a request to "https://api.bitfinex.com/v2/auth/r/wallets" I got 500 without any description.

It does not happen often. Any ideas what is the problem?

**Comment by f3rno** [comment]
@ddeath we need more info to debug this; any chance you can provide your IP & specific time frame of when you last saw this?

**Comment by ddeath** [comment]
@f3rno could you provide some email address where I can send that information?

**Comment by f3rno** [comment]
Closing as outdated, we couldn't find anything unique on the backend.
