### ISSUE TITLE
Not indexed response arrays

### ISSUE THREAD

**Issue by bachilli** [bitfinexcom/bitfinex-api-node#278]
Why the responses from websockets are not indexed, like ['order_id' : 999009, "status":status]. All responses returns are in raw arrays that are difficult to understand and can broke easily if the api are updated.

**Comment by f3rno** [comment]
@bachilli they are like this for performance reasons; raw arrays have a smaller size on the wire, and if you use the built-in models you don't need to worry about them, as they are handled automatically (and broken out for easier reading): https://github.com/bitfinexcom/bitfinex-api-node/blob/master/lib/models/candle.js

**Comment by bachilli** [comment]
@f3rno I agree with the performance reasons. But the bitfinex will never change this model? If no, thats ok. 

- Using this same contact... How I request for API Rate limit increase? Its ok to send orders via WS, but If my connection drops, I lost a lot of information and cant retrieve this lost info with REST APi bacause the endpoints are rate limited. Theres other way to do this ou require more rate in the restful api?
