### ISSUE TITLE
Orders snapshots/Trades snapshops don't return executed orders

### ISSUE THREAD

**Issue by bachilli** [bitfinexcom/bitfinex-api-node#279]
Orders snapshots or/and Trade snapshops doesnt return executed/filled orders. So, if my connection drops, I lost the status.

**Comment by ksergey** [comment]
Use rest for that

**Comment by bachilli** [comment]
@f3rno can you help me with that question?

**Comment by f3rno** [comment]
@bachilli RESTv2 is the way to go for this, WSv2 should only be used for realtime data. The idea is, ws2 provides everything you need to maintain a running copy of your current account state. So you receive an initial snapshot of your currently open orders, along with updates for them as they occur. Any historical needs should be covered by RESTv2, and the account limits are more than reasonable for querying historical data.

An idea: maybe only query RESTv2 if your connection drops, and specifically after reconnecting if your snapshots don't match. Then you could query for specific order trades, etc.

Feel free to provide more details if you're still looking for a solution. I recommend caching data locally if you are querying for it often & repeatedly.
