### ISSUE TITLE
api.bitfinex.com | 520: Web server is returning an unknown error

### ISSUE THREAD

**Issue by ddeath** [bitfinexcom/bitfinex-api-node#288]
Hello

I just get an error during the post call `https://api.bitfinex.com/v2/auth/r/wallets` around 2018-04-12 05:40:20 utc

The response body of that call is json encoded HTML page saying also:

`There is an unknown connection issue between Cloudflare and the origin web server. As a result, the web page can not be displayed.`

It is probably not an error with this library but with the server... Also there was no info about downtime it that time....

Thank you

**Comment by f3rno** [comment]
Closing since, as you said, this was a server issue & should be sporadic. If you still see it, please re-open
