### ISSUE TITLE
[WS2]: Empty order-info field on notification (ou-req) with error

### ISSUE THREAD

**Issue by escoman** [bitfinexcom/bitfinex-api-node#299]
My request: [0, "ou", null, { "id": 10979800191, "amount": "0.70", "price": "15.85" }]

Server response: [0,"n",[1524135087973,"ou-req",null,null,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0,null,null,null,null,null,null,null,null],null,"ERROR","Invalid order: minimum size for ETC/USD is 0.8"]]

So, I can not find out which order sent the error.

If no error, server response is normal: [0,"n",[1524132548393,"on-req",null,null,[10979800191,null,1524132548256,"tETCUSD",null,null,1,1,"LIMIT",null,null,null,null,null,null,null,16.08,null,null,null,null,null,null,0,null,null,null,null,null,null,null,null],null,"SUCCESS","Submitting limit buy order for 1.0 ETC."]]

**Comment by f3rno** [comment]
@escoman escalated internally, I'll get back to you

**Comment by f3rno** [comment]
@escoman this has been fixed and will be deployed in the next few hours, you should then receive at least the order ID in the response payload :slightly_smiling_face:
