### ISSUE TITLE
Update an existing order

### ISSUE THREAD

**Issue by ksergey** [bitfinexcom/bitfinex-api-node#300]
Hello,

Could you please clarify how Update Order (https://docs.bitfinex.com/v2/reference#update-order) works?
What's is AMOUNT and DELTA in this case mean? It's not clear from docs.

Thanks

**Comment by f3rno** [comment]
@ksergey does this help? https://github.com/bitfinexcom/bitfinex-api-node/pull/294

The `delta` is used to increase/decrease the order amount without changing its position in the queue.

**Comment by ksergey** [comment]
@f3rno 
Is it possible to increase order amount for filled order?
Is it possible to update only order price?
