### ISSUE TITLE
API Key invalid

### ISSUE THREAD

**Issue by L-S-Ross** [bitfinexcom/bitfinex-api-node#302]
tried 3 times from scratch to do this, each time I got API key invalid. Used the login method on the bitfinex documentation and it logs in with that API key fine.

**Comment by ddeath** [comment]
@L-S-Ross can you post snippet of your code which you use?

Also which version of lib do you use?

**Comment by L-S-Ross** [comment]
ws.on('open', () => { // wait for socket open
  ws.auth()           // & authenticate

  debug('open')
})

ws.on('error', (err) => {
  debug('error: %j', err)
})

ws.once('auth', () => {
  debug('authenticated')

  // do something with authenticated ws stream
})

// Register a callback for any order snapshot that comes in (account orders)
ws.onOrderSnapshot({}, (orders) => {
  debug(`order snapshot: ${JSON.stringify(orders, null, 2)}`)
})

// Open the websocket connection
ws.open()

**Comment by ddeath** [comment]
@L-S-Ross and where do you insert api key?

About that data, take a look at [this example](https://github.com/bitfinexcom/bitfinex-api-node/blob/master/examples/ws2/orders.js) This lib has models classes for data.

**Comment by L-S-Ross** [comment]
thanks ddeath, I didn't know i had to put the api key in again, I authenticated like the v2 docs said, on the bfx website. Soooo confusing, I can see the data, but cant get at it. I guess it's case closed, I'm to blame :(
