### ISSUE TITLE
is the apiKey required for public methods?

### ISSUE THREAD

**Issue by aryeharmon** [bitfinexcom/bitfinex-api-node#306]
the api key should not be required for public methods. however i can not getting any data from ws.onTrades

**Comment by ddeath** [comment]
```
ws.subscribeTrades(
  'SYMBOL'
);

ws.onTradeEntry({ pair: 'SYMBOL' }, (data) => {
   console.log(data);
});
```

You probably have to subscribe to the trades

**Comment by f3rno** [comment]
Yes, @ddeath is right. @aryeharmon can you share your code?
