### ISSUE TITLE
Rest v2 `wallets` available balance is null

### ISSUE THREAD

**Issue by askmike** [bitfinexcom/bitfinex-api-node#321]
Problem:

    const bfx = new Bitfinex.RESTv2({apiKey: 'x', apiSecret: 'y', transform: true});
    bfx.wallets(console.log);

outputs:

    { err: null,
      data: 
       [ Wallet {
           domain: null,
           _events: {},
           _eventsCount: 0,
           _maxListeners: undefined,
           type: 'funding',
           currency: 'BTC',
           balance: 0.01511371,
           unsettledInterest: 0,
           balanceAvailable: null },
         Wallet {
           domain: null,
           _events: {},
           _eventsCount: 0,
           _maxListeners: undefined,
           type: 'exchange',
           currency: 'NEO',
           balance: 0.00494487,
           unsettledInterest: 0,
           balanceAvailable: null },
         Wallet {
           domain: null,
           _events: {},
           _eventsCount: 0,
           _maxListeners: undefined,
           type: 'exchange',
           currency: 'USD',
           balance: 13.97576373,
           unsettledInterest: 0,
           balanceAvailable: null } ] }

with `balanceAvailable` set to `null`, which is not true. The  v1 API correctly outputs:.

    { type: 'exchange',
       currency: 'usd',
       amount: '13.97576373',
       available: '13.97576373' }

Doesn't seem to be transform issue, as this lib receives `[ 'exchange', 'USD', 13.97576373, 0, null ]` from the API.

Actual question: Which API should be used? Is v2 finished or still in development?

**Comment by ddeath** [comment]
@askmike the null is valid value. In the api v2 you have to use different call which will calculate available balance:

https://bitfinex.readme.io/v2/reference#rest-auth-calc-bal-available

**Comment by askmike** [comment]
@ddeath thanks for clarifying. I guess the easiest for now is to simply query the v1 endpoint instead of fetching the new endpoint per currency you need whenever you see a `null`.
