### ISSUE TITLE
Event "info"

### ISSUE THREAD

**Issue by ksergey** [bitfinexcom/bitfinex-api-node#322]
Hello,

Today my app received `info` which looks like:
```
{"event":"info","version":2,"platform":{"status":1}}  
```

The field `platform` not mentioned in official docs. Could you please clarify? Is it the same which returns by `Platform Status` request?

**Comment by f3rno** [comment]
@ksergey yes, a value of '0' signals that the platform is under maintenance. Have a look here: https://github.com/bitfinexcom/bitfinex-api-node/blob/master/lib/transports/ws2.js#L1013

I've updated the docs here: https://docs.bitfinex.com/v2/docs/ws-general#section-info-messages
