### ISSUE TITLE
Docs Request: Difference between R0/P* OBs

### ISSUE THREAD

**Issue by kiko35** [bitfinexcom/bitfinex-api-node#323]
Hello,

I don't really understand the description on the bitfinex's doc for the raw books which is "These are the most granular books." What's the difference with the orderbook?

Thanks

**Comment by f3rno** [comment]
@kiko35 the raw order books return the top N bid/ask _orders_ (depending on the book length, i.e. N=100), while ordinary OBs provide you the top N bid/ask price levels (so 2 orders at the same price level appear as a single price level).

I will update the docs to clarify this.

**Comment by kiko35** [comment]
thanks

**Comment by f3rno** [comment]
@kiko35 I will keep this open until the repo docs are updated.
