### ISSUE TITLE
Invalid input for order update

### ISSUE THREAD

**Issue by mixitka** [bitfinexcom/bitfinex-api-node#325]
Hi,

I tried to sent the following json message to update my order (https://bitfinex.readme.io/v2/reference#update-order):

```
[0,"ox_multi",null,[["ou",{"id":MY_ORDER_ID_AS_INTEGER,"price":"7760.10"}]]]
```

but I'm getting the following error response:

```
[0,"n",[1525700930498,"ox_multi-req",null,null,null,null,"ERROR","input: invalid"],5703]
```

What is wrong? Does `ox_multi` support order update? (I use ox_multi because I may want to update more orders in general)

Thanks,
Martin

**Comment by mixitka** [comment]
@f3rno Any idea, please?

**Comment by f3rno** [comment]
`ox_multi` doesn't support `ou` (apologies for the late response, I was waiting for an answer internally and forgot to update)
