### ISSUE TITLE
Questions about Update Order

### ISSUE THREAD

**Issue by ksergey** [bitfinexcom/bitfinex-api-node#330]
Could you please clarify what values should be in fields `AMOUNT` and `DELTA` in `Update Order` message?

For example, in `New Order` `AMOUNT` should be positive if order side is buy and negative if order side is sell. For `Update Order` the same rules?

The same question for `DELTA`. `Update Order` could decrease order `AMOUNT` via `DELTA`?

This is not clear in official documentation

**Comment by tux-00** [comment]
AMOUNT : https://bitfinex.readme.io/v2/reference#ws-auth-orders

**Comment by ksergey** [comment]
Resolved
