### ISSUE TITLE
Orders via WSS or REST?

### ISSUE THREAD

**Issue by xFFFFF** [bitfinexcom/bitfinex-api-node#339]
In the case of stream, it is known that websocket is faster. However, is the order so? I mean: connect-> send request on every placing order
If it is faster than in REST, what are the disadvantages of websocket?

**Comment by Shigawire** [comment]
The idea is to remain connected to the websocket connection the whole time and then send the new order-command when required.

**Comment by f3rno** [comment]
@xFFFFF You can keep the connection open between multiple orders :) The WSv2 API is meant for receiving realtime data/creating & managing orders, while RESTv2 is primarily for querying historical data.
