### ISSUE TITLE
Detemining if a limit order is executed as a Taker trade

### ISSUE THREAD

**Issue by Feynz** [bitfinexcom/bitfinex-api-node#345]
When making Limit order I know the "te" and "tu" messages indicate if a trade is a taker, though the "oc" is faster. Is there anyway of determining if it's a Taker with the "oc" stream?

**Comment by f3rno** [comment]
No, currently the maker/taker data is not provided on the `o*` packets.

**Comment by Feynz** [comment]
Turns out you can. If an 'oc' is received for an order and no 'on' was received previously, the limit order is a taker. Not sure if this trick works for partial takers, ie, is the 'ou' received before the 'on' in the case of a partial taker?
