### ISSUE TITLE
How to unsubscribe from WS2 Ticker

### ISSUE THREAD

**Issue by balin77** [bitfinexcom/bitfinex-api-node#349]
Hi guys, 

Im having an issue - probably due to the lack of experience. I subscribed successfully to the WS Ticker channel:
```
ws.on("open", () => {
   ws.subscribeTicker("BTCUSD")
```
The response is:
```
[ 3316,
  [ 6455,
    43.99812575,
    6455.1,
    44.96736665,
    -68,
    -0.0104,
    6455,
    12527.05620449,
    6540,
    6370.76958739 ] ]
```
Now I would like to unsubscribe, which until now I couldnt get done. I tried

```
  ws.on("open", () => {
    ws.unsubscribeTicker("BTCUSD")
```
and
```
  ws.on("open", () => {
    ws.unsubscribeTicker
```
but I didnt even receive an answer. When I tried to unsubscribe by channel_id like that
```
  ws.on("open", () => {
    ws.unsubscribe(channelId)
```
I received this answer: 
```
Object {event: "error", msg: "unsubscribe: invalid", chanId: 3316, code: 10400}
```
As far as I can judge, the chanId is correct though. What am I doing wrong? 

Thanks for helping

Balin

**Comment by f3rno** [comment]
@balin77 a bit late, but you should prefix the symbol with `t` for trading pairs, or `f` for funding pairs (in your case, it should be `tBTCUSD`)

Then simply provide the same symbol to `unsubscribeTicker()`
