### ISSUE TITLE
Strange symbol naming

### ISSUE THREAD

**Issue by corpix** [bitfinexcom/bitfinex-api-node#352]
What is `t` in symbol name `tETHUSD`?
> [Example](https://github.com/bitfinexcom/bitfinex-api-node#ws2-example-sending-an-order--tracking-status) from readme.
``` javascript
ws.once('auth', () => {
  const o = new Order({
    cid: Date.now(),
    symbol: 'tETHUSD',
    amount: 0.1,
    type: Order.type.MARKET
  }, ws)
// ...
```

And how it differs from `pair` `BTCUSD` here?
> [Example](https://github.com/bitfinexcom/bitfinex-api-node#ws2-example-subscribe-to-trades-by-pair) from readme.
``` javascript
ws.onTrades({ pair: 'BTCUSD' }, (trades) => {
  console.log(`trades: ${JSON.stringify(trades)}`)
})
```

**Comment by vsly-ru** [comment]
simply use `'ETHUSD'` for `pair` and `'t'+pair` for symbols.

**Comment by corpix** [comment]
@vsly-ru sorry, but this does not answers the original question. I want to understand the difference between `ETHUSD` and `tETHUSD`. In my opinion "blindly use `this` instead of `that`" is incorrect behaviour.

I have a guess about `t` prefix. Probably it means **t**rading. I came to this conclusion because I have seen `fETHUSD` symbol in the API docs and there are two(or more?) "market types" on bitfinex: **t**rading and **f**unding.
But those are only guesses, API docs does not shed any light on this.

**Comment by f3rno** [comment]
@corpix You are correct, `t*` pairs are trading pairs, and `f*` funding pairs
