### ISSUE TITLE
Statuses explanation

### ISSUE THREAD

**Issue by davidjirovec** [bitfinexcom/bitfinex-api-node#358]
`WIDTH CANCELED was: PARTIALLY FILLED @...` - What does it mean?
`insufficient balance (g1) was: partially filled @...` - What does this mean? I had enough balance, otherwise I would not be able to place the limit order, right?

**Comment by vsly-ru** [comment]
What type of order you using exactly? `type: 'LIMIT',` ?

**Comment by ilyacherevkov** [comment]
same error. Wtf? 

Limit order type used

**Comment by davidjirovec** [comment]
I've contacted Bitfinex support:

Bitfinex Support <support@bitfinex.com>
Jul 5
to me 
Hello david jirovec

Thanks for your email.

I understand you would like clarity on the status messages in your order reports, is that correct?

Cancelled = indicates that your order had not been executed in full.
Partially filled = indicates that part of your order that has been executed, in line with the fluctuating matched price and amount.
Insufficient balance = indicates that you had set a limit order, which the system had tried to match, however your account balance had run out of funds to execute the remaining amount. E.g. You set a limit order for 10 BTC at $1000 per coin, as the market is fluctuating your fees may go from taker to maker hence the hairline difference (or dust amounts) results in you purchasing 9.99999999 BTC with all the available funds you have. 

Kind regards, 
Bitfinex.com
support@bitfinex.com
image

image image image image
We hope this response has sufficiently answered your questions. If not, please do not send another email. Instead, reply to this email. 

Submitted: 2018-07-04 14:08
Subject: Order statuses
Ticket number: #930310

WIDTH CANCELED was: PARTIALLY FILLED @... - What does it mean?
insufficient balance (g1) was: partially filled @... - What does this mean? I had enough balance, otherwise I would not be able to place the limit order, right?

[System Info]:
- Modal path: question > trading

David Jirovec <david.jirovec@gmail.com>
Jul 5
to Bitfinex 
Hi,

thanks for response, but I need some more clarification :)


WIDTH CANCELED was: PARTIALLY FILLED @ this order is partially filled, but I don't understand what the "WIDTH CANCELED" in description means.

insufficient balance (g1) was: partially filled @ what is the meaning of the "g1"? Is it described somewhere in some documentation?

Thanks


Bitfinex Support <support@bitfinex.com>
Jul 5
to me 
Hello david jirovec

Thanks for your email.

The prompt WIDTH indicates to us that you had placed a trade would moved the market by more than 5%.

The g1 code is not described in our public documentation. For intensive purposes, please refer to the explanation I have provided previously.


David Jirovec <david.jirovec@gmail.com>
Jul 5
to Bitfinex 
Ok thanks.

Are these error codes somewhere documented, so I can prepare for more possible errors not yet known to me?


Bitfinex Support <support@bitfinex.com>
Jul 5
to me 
Hello david jirovec

These codes are not documented in the public domain as the intention is for our clients to contact us if anything appears amiss with their orders/ trades/ balances. It is also to allow for changes to be made to the descriptive text without causing more confusion to our clients.

Therefore it is imperative that you enquire with support desk for any doubts or concern. Support desk will guide you through any interpretation if and when you require more information on an order you have executed.


David Jirovec <david.jirovec@gmail.com>
Jul 24
to Bitfinex 
Thanks. Is it possible for me to know before I place an order that it will probably end with "WIDTH CANCELED"?


Bitfinex Support
Jul 24
to me 
Hello David Jirovec

Thanks for your follow up email.

As for your query, that will not be possible.
