### ISSUE TITLE
Time-in-Force (TIF) orders

### ISSUE THREAD

**Issue by ilyacherevkov** [bitfinexcom/bitfinex-api-node#359]
As per [changelog page](https://docs.bitfinex.com/v2/docs/changelog#section-v2018-06-08) new type of order, namely Time-in-Force (TIF) was recently introduced. Any ideas how to pass params to place this type of order? Documentation was not updated.

**Comment by f3rno** [comment]
The relevant key to pass to `on` has been added to the docs page: https://docs.bitfinex.com/v2/reference#ws-input-order-new
