### ISSUE TITLE
Error: invalid seq # again

### ISSUE THREAD

**Issue by vsly-ru** [bitfinexcom/bitfinex-api-node#361]
My script was working fine until i decided to cancel an order for the first time:
```
ws2.cancelOrder(EV.id).then(() => {
  clog('~','order has been canceled, ready to place new one',false);
});
```
it works fine (log been displayed) and then `ws2.on('error', (err) =>` triggers many times:
```
ws2!err: Error: invalid seq #; last 20, got 22
ws2!err: Error: invalid seq #; last 20, got 23
ws2!err: Error: invalid seq #; last 20, got 24
ws2!err: Error: invalid seq #; last 20, got 25
//etc
```
Nothing else is working in the ws2 (`= bfx.ws(2)`) afterwards, it only produces errors.
Just disabled `seqAudit` for now (is it ok to keep it like this?)

**UPD:** After `seqAudit` was disabled, `ws2.onTrades({ pair: cPair }, (trades) => {` doesn't receive trading entries anymore (which was receiving both `te` and `tu` events **btw**, which i can't distinguish so it was doubling. **But** `ws2.onTradeEntry({ pair: cPair }, (trades) => {` suddenly starts working. **But** after i successfully  made an order `onTradeEntry` also receives some useless information which crashes the script.
```
for(trade of trades){
             ^

TypeError: trades is not iterable
```

**Comment by lostless13** [comment]
I've noticed this too. Basically anytime you try to cancel an order it doesn't work correctly. My suspicion is that there is a promise that doesn't resolve correctly.

**Comment by f3rno** [comment]
@lostless13 @vsly-ru can you both test this again with latest `master`? It may have been fixed in https://github.com/bitfinexcom/bitfinex-api-node/pull/379 if the issue was due to an error notification.

@vsly-ru the trades issue has been fixed in https://github.com/bitfinexcom/bitfinex-api-node/pull/380

**Comment by lostless13** [comment]
@f3rno will do. Would it be possible to update the npm package?

**Comment by f3rno** [comment]
@lostless13 the package has been updated

**Comment by npomfret** [comment]
This is still a problem for me on 2.0.4
