### ISSUE TITLE
Can't transfer funds from Exchange to Margin wallet

### ISSUE THREAD

**Issue by STOpandthink** [bitfinexcom/bitfinex-api-node#362]
I'm using `v1/transfer` endpoint, and getting the following error: "USD cannot be used for Margin Trading. Transfer to Margin wallet not possible."

I've checked API permissions for my key, and everything is enabled.

**Comment by STOpandthink** [comment]
Hello? This is still an issue. It's big problem, because we only have the API key to access the account, so there's currently no other way to transfer funds between wallets.

**Comment by lellywang** [comment]
i have the same issue

**Comment by STOpandthink** [comment]
I received a reply from their team. My issue was that I specified "usd" not "USD". Sigh.
