### ISSUE TITLE
How to use websocket 2 Authenticated filter

### ISSUE THREAD

**Issue by trimup** [bitfinexcom/bitfinex-api-node#363]
i use no Channel filters connet is ok!
payload ={"apiKey":"O8L","authNonce":"1531827428723041","authPayload":"AUTH1531827428723041","authSig":"f","event":"auth","calc":1}
connet response:
{"event":"auth","status":"OK","chanId":0,"userId":"","auth_id":"3","caps":{"orders":{"read":1,"write":1},"account":{"read":1,"write":0},"funding":{"read":1,"write":1},"history":{"read":1,"write":0},"wallets":{"read":1,"write":1},"withdraw":{"read":0,"write":0},"positions":{"read":1,"write":1}}}
But i use filter connet not response!
payload =
{"apiKey":"8L","authNonce":"1531827597061623","authPayload":"AUTH1531827597061623","authSig":"cc","event":"auth","calc":1,"filter":["trading","funding","wallet","wallet-exchange-BTC","algo","balance","notify"]}
How to use websocket 2 Authenticated Channel  filter

**Comment by vsly-ru** [comment]
This is a **node.js** **lib** project page, we simply use it. 
In your case: idk what is `Authenticated Channel filter` you mentioned (can't even google it).
If you need to subscribe to trades, wallet, balance etc. do it manually by sending messages like: 
```
{
   "event": "subscribe",
   "channel": CHANNEL_NAME
}
```
then you get response:
```
{
   "event": "subscribed",
   "channel": CHANNEL_NAME,
   "chanId": CHANNEL_ID
}
```
keep `CHANNEL_ID` somewhere and compare it to `CHANNEL_ID` of updates you'll receive.
Good luck with your project and please don't post your questions here.
1. This is for `ISSUES` not `questions`
2. This is `bitfinex-api-node` lib, not API support forum.
Thank you.

PS: [RTFM](https://docs.bitfinex.com/v2/reference#account-info )

**Comment by mattfilippone** [comment]
what are the possible CHANNEL_NAMES - no where on their site or docs do they list them.  They have section titles such as "Position Snapshot", "Order Updates" but those strings don't work and neither do the short hand versions 'te', 'ts', 'ps'.  What gives?
