### ISSUE TITLE
Websocket v2 sequence auditing doesn't handle error responses correctly

### ISSUE THREAD

**Issue by lostless13** [bitfinexcom/bitfinex-api-node#367]
If a request (ie sendOrder method or cancelOrder method) fails (ie rejects the promise) the sequence number auditing begins to report errors.

Steps to reproduce:
1. Enable seq Auditing
2. Open and authenticate WebSocket. (Version 2)
3. Send Order with invalid symbol or amount.
4. Promise is rejected
5. Websocket begins to report sequence errors.

Sample output after cancelling an order:
![image](https://user-images.githubusercontent.com/24193723/43564123-8d3340f6-95e2-11e8-8b61-56e0c5f952a9.png)

I believe that this is due to how the library handles promise rejections but I haven't looked into the issue in detail. My guess is when a promise is rejected (or error is thrown) due to an error response from the api, the sequence auditing code does not execute due as it is not properly handled in the catch block.

**Comment by nonamenonumber** [comment]
Getting same issue when testing using a read-only api key:
![image](https://user-images.githubusercontent.com/709935/44033093-2d474188-9f01-11e8-8c08-5c376802b1a5.png)

**Comment by npomfret** [comment]
I still get this when cancelling an order.  Don't think it's to do with errors though.  I'm just creating an open order.  Then restarting my app and cancelling it.
