### ISSUE TITLE
Websocket Changes Coming 2018

### ISSUE THREAD

**Issue by electic** [bitfinexcom/bitfinex-api-node#369]
http://blog.bitfinex.com/api/api-update-september-2018/

If you subscribe to more than 50 subscriptions for trades, will the library create another websocket connection?

**Comment by algotek** [comment]
I have no idea who come up with this, but are they realize that all and every library need to be updated and all direct api users need to create their own 'load balancer' because of this?

**Comment by f3rno** [comment]
@algotek we will provide transparent support for an internal connection pool via our API libraries (this one included)

**Comment by algotek** [comment]
Create a V3 endpoint , introduce the breaking changes there , and enforce new users/api keys to use V3, but do not trash your existing api users. Almost certain you have no idea how big the impact will be. Half of your api users will fall off the cliff.

**Comment by algotek** [comment]
or simply change all relevant V2 endpoints on sept 1 , so all api users forced to stop. This make sure old api codes won't run into trouble.

**Comment by prdn** [comment]
There are users that subscribe to 3k channels (150 books, all trades, all candles on a single book).
Ensuring the stability and the proper usage of the websocket feed is our priority. We gave 1 month and will work to adjust this library to support the change.

**Comment by algotek** [comment]
Why all users need to suffer from a few 3K subscriber, it is not clear. 1 month for all api users is not enough, and the fact that 'old' api codes can continue to run silently is also disturbing.

**Comment by algotek** [comment]
Not sure if bitfinex can differentiate between let's say introducing a v3 with new changes, and then turn off v2 , 
or keep the v2 but put a few razor blade in it here and there?

**Comment by algotek** [comment]
Just for example, searching on bitfinex c# libraries (https://github.com/search?l=C%23&q=bitfinex&type=Repositories) , there are about 20 results , 1 updated recently, and they have no idea of the sept1 change either. Thats why I said you blow your api users out of water. (number of custom libraries for all languages: ~500)

**Comment by prdn** [comment]
Most of them do not seem to support websockets. Also I think that the best way to deal with this is from the user side : https://twitter.com/paoloardoino/status/1023584788081516544?s=19

It's few lines of code really

**Comment by algotek** [comment]
CHANNEL_ID lost its purpose, since it is not unique anymore across multiple websocket instance.
CHANNEL_ID could be replaced with ticker name.

**Comment by algotek** [comment]
CHANNEL_ID lost its purpose, since it is not unique anymore across multiple websocket instance.

**Comment by algotek** [comment]
Does ping the bitfinex server neccessary? I see the websockets which subscribed for public data stucked, with no response whatsoever, with single websocket this never occured before. Did you test this multi websocket connection at all? Why data websockets hang indefinitely?

**Comment by slidenerd** [comment]
if you are gonna do this, I have one suggestion for you, kindly add an option to subscribe to all tickers over websocket instead of sending a subscription message for each pair, take a look at the other exchange codebases, none of them that I am aware of require one subscription per pair to retrieve all tickers, the purpose of a ticker is to give an overall state of the market on that exchange, why would someone subscribe to only 1 pair for ticker data?
