### ISSUE TITLE
orderbook websocket events returns wrong data (applicable to API v1 and v2)

### ISSUE THREAD

**Issue by dutu** [bitfinexcom/bitfinex-api-node#37]
`orderbook` events return wrong data: values for price and count are swapped.
Example:
```
{
  "price": 2519820957,
  "count": 0.049631,
  "amount": 9.47126434
}
```

**Comment by prdn** [comment]
@robertkowalski please take care of this

**Comment by robertkowalski** [comment]
Hi @dutu,

thanks for the report!

I just tried to reproduce the issuee.

The WS API v2 returns for me:

```
Order book: [ 1774.2, 4, 8.1223 ]
Order book: [ 1772.8, 2, 0.8 ]
Order book: [ 1772.7, 2, 1.3235 ]

[...snip]
```

The WS v1 API returns for me:

```
Order book: { price: 1775.2, count: 1, amount: 0.05 }
Order book: { price: 1774, count: 1, amount: 0.015 }
Order book: { price: 1773, count: 1, amount: 0.01 }

[...snip]
```

1) Where do you get the values from? Can you send an example snippet?
2) What pairs / orders are you looking at? (I used `BTCUSD` in my test)

--- 

Example code:

```js
const BFX = require('.')

const API_KEY = 'my-api-key'
const API_SECRET = 'my-secret'

const API_VERSION = 1

const bws = new BFX(API_KEY, API_SECRET, API_VERSION).ws

bws.on('open', () => {
  bws.subscribeOrderBook('BTCUSD')
})

bws.on('orderbook', (pair, book) => {
  console.log('Order book:', book)
})

bws.on('error', console.error)
```

**Comment by dutu** [comment]
I was using the ETHBTC pair, but can't reproduce the issue anymore. I'm getting the correct result.
Thank you for your response, I'm closing the issue and report back later if needed.

**Comment by dutu** [comment]
I'm getting this error for "raw books"
`bws.subscribeOrderBook('ETHBTC', 'R0');`

Also the documentation for the expected response is unclear/incomplete: 
v1: http://docs.bitfinex.com/v1/reference
V2: http://docs.bitfinex.com/v2/reference#ws-public-order-books

**Comment by robertkowalski** [comment]
@dutu thank you, was able to reproduce. seems the websocket-server sends the wrong response. i'll keep you posted!

**Comment by prdn** [comment]
@robertkowalski @dutu seems that the websocket servers send the right payload
```
[128855,[2553531698,1755.9,0.629]]
```
You need to look at this part of the documentation
http://docs.bitfinex.com/v2/reference#ws-public-raw-order-books

In my opinion is the lib that should handle it

**Comment by dutu** [comment]
It looks that the precision levels P and R0 are not handled differently (as they should since there is a different structure)
https://github.com/bitfinexcom/bitfinex-api-node/blob/master/ws.js#L276-L308

**Comment by robertkowalski** [comment]
@dutu just pulled it out of the backlog :)

**Comment by robertkowalski** [comment]
@dutu this is fixed now.

for all breaking changes, see https://github.com/bitfinexcom/bitfinex-api-node#version-100-breaking-changes

**Comment by dutu** [comment]
tx, for when is the npm release planned?

**Comment by robertkowalski** [comment]
i hope next week.
