### ISSUE TITLE
argument length for orderbook (websocket)

### ISSUE THREAD

**Issue by dutu** [bitfinexcom/bitfinex-api-node#38]
What is the meaning/use of argument `length` here:
https://github.com/bitfinexcom/bitfinex-api-node/blob/master/ws2.js#L180-L187

```
  subscribeOrderBook (symbol = 'tBTCUSD', precision = 'P0', length = '25') {
    this.send({
      event: 'subscribe',
      channel: 'book',
      symbol,
      prec: precision,
    })
  }
```

Same question for API v1

**Comment by prdn** [comment]
@dutu http://docs.bitfinex.com/v2/reference#ws-public-order-books the length should me mapped to the `len` parameter expected when you subscribe to websocket books.

**Comment by dutu** [comment]
this doesn't seem to be the case in the code

**Comment by robertkowalski** [comment]
was able to reproduce the issue. yes, that's a bug. fix is on the way.
