### ISSUE TITLE
How do we use methods like onMaintenanceStart with the new ws2_manager wrapper?

### ISSUE THREAD

**Issue by TehCrucible** [bitfinexcom/bitfinex-api-node#389]
If the manager creates new sockets as necessary, how can we attach maintenance and restart listeners to each socket to ensure we respect the API restart requests and gracefully handle re-subscribing etc.

I would think that we don't want to be managing this logic on each underlying ws2 instance?  Generally speaking, if we have to disconnect, they all have to disconnect and when we want to reconnect, we probably want to use the manager to automatically provision new connections as necessary right?

Forgive me if this is a dumb question with a simple answer.

**Comment by f3rno** [comment]
@TehCrucible very good question, I did not realize this was impossible with the manager. I've opened https://github.com/bitfinexcom/bitfinex-api-node/pull/391 and it should be merged in shortly
