### ISSUE TITLE
BTCUSD raw order book has strange price precisions

### ISSUE THREAD

**Issue by happypepper** [bitfinexcom/bitfinex-api-node#395]
I subscribed to the BTCUSD raw order book and noticed that there are some orders with strange prices:
```[159253,[[16547280766,6188.818114,0.15],[16547234666,6188.801069,0.4],[16547217150,6188.8,0.006],[16547217884,6188.8,0.012],...```
The price precision should be 5 only right?

**Comment by ksergey** [comment]
@happypepper I have the same issue since last year in market data. The actual number of digits after dot in your example should be 1 (not 5). Check this https://support.bitfinex.com/hc/en-us/articles/115000371105-How-is-precision-calculated-using-Significant-Digits

**Comment by happypepper** [comment]
Yes, it should have 1 digit after the dot, which would mean a precision of 5.

**Comment by ojoaofernandes** [comment]
Hi guys,

It isn't a lib issue. Unluckily it's coming from the Bitfinex API.
@f3rno, could you please close this issue?

Cheers,
João Fernandes

**Comment by f3rno** [comment]
Yes, this is fine; it's due to the virtual order books price calcs (JPY, USD, EUR, etc)
