### ISSUE TITLE
Please provide a method for REST v1 to post "ReduceOnly" orders

### ISSUE THREAD

**Issue by tr91** [bitfinexcom/bitfinex-api-node#402]
When are you planning to port this over to REST v1 as well? instead of only keeping it on WSv2?

**Comment by f3rno** [comment]
RESTv1 is deprecated and does not receive updates. We are planning on releasing RESTv3 soon :)

**Comment by tr91** [comment]
ETA? Planning, your v2 has been in BETA for 1 year +

**Comment by f3rno** [comment]
v3 will be out next year, but I don't have an exact ETA

**Comment by tr91** [comment]
So basically the same forever beta as v2? All it takes is for you to make one more variable that accepts boolean like "is_hidden"

**Comment by f3rno** [comment]
Alright, I will push for a full-featured order submit method on RESTv2.
