### ISSUE TITLE
api proposal: constructor & options

### ISSUE THREAD

**Issue by robertkowalski** [bitfinexcom/bitfinex-api-node#41]
Right now the main-entry point, `index.js` initiates both the websocket and rest clients. This is usually unnecessary, as users will go with the rest **or** the ws client and leads to side effects.

For instance, when initialising the class, and using the http client in an integration test, the websocket code will cause the node.js process to wait & listen and not to exit.

Proposal:

Return the initiated client depending which method is called. The API should support chaining.

```js
const bfx = require('bitfinex-api-node')
const client = new Bfx(options).http()

const cb = () => {}
client.tracker(cb)

// chaining:

new Bfx(options).http().tracker()
```

For websockets:

```js
const BFX = new Bfx(options)
const client = BFX.ws()
```

What do you think?

**Comment by prdn** [comment]
I like it @robertkowalski

**Comment by robertkowalski** [comment]
Cool! We just have to think about a migration strategy for old users, lets chat about that...

**Comment by prdn** [comment]
@robertkowalski what about a major release that changes the sem-version?

**Comment by dutu** [comment]
@prdn, not even v0.30 is published on npm. At this stage it's confusing which version is good to use.
There are unaddressed open issues, shouldn't these have priority over non-essential changes such as code writing style changes?
Any plan to address the open issues (some are several months old)?

**Comment by prdn** [comment]
@dutu part of the effort we are trying to put in place is to reach quickly a version of this library that is stable and can be used as a stable ground work for the future.
Those issues should be addressed while clearing and improving the code base.

**Comment by prdn** [comment]
@dutu I also would like that this library becomes a real community project, so any help is really appreciated

**Comment by dutu** [comment]
@prdn, fair enough. However, shouldn't functionality issues be addressed first, over other non-essential changes?
Functionality issues, some several months old are still open and a solution is not provided on npm.
I recently opened 2 issues (and have another older one), and  there is no sign of response or feedback, hence motivation to contribute more is low.

**Comment by prdn** [comment]
@dutu yes and I replied to you :-) we'll take care of these issues

**Comment by robertkowalski** [comment]
just a quick explanation why this change is important:

as described, the websocket is created every time in the constructor, even if you don't use it. 

for quality and reliability we rely on our testsuite. so every time someone calls `new BFX` in the testsuite, a connection to the bitfinex liveservers is established, creating load on the servers, and then leading to a `429` as too many connection are opened. today i crossed the point where all runs failed because of the issues.

**Comment by robertkowalski** [comment]
merged.

**Comment by robertkowalski** [comment]
turns out this got somehow lost

**Comment by robertkowalski** [comment]
:(

**Comment by glaucoheitor** [comment]
This should be addressed so we dont get that much 429 errors.
Even using autoOpen: false it didnt resolved 100%.

I am using a time counter to not send more than one request every 2s.
