### ISSUE TITLE
api timeout

### ISSUE THREAD

**Issue by tttttvf** [bitfinexcom/bitfinex-api-node#419]
Recently when I was using the V1 version of the api, I encountered a program call connection timeout, but the browser and postman had no problem. What happened? I just used the public API and asked https://api.bitfinex.com/v1/pubticker/BTCUSD
![image](https://user-images.githubusercontent.com/23305591/46995220-50e88180-d14a-11e8-962f-8dc4aa18bbbf.png)
![image](https://user-images.githubusercontent.com/23305591/46995260-8db47880-d14a-11e8-8c04-dbea709c35c7.png)

**Comment by f3rno** [comment]
@tttttvf the frontend likely retries the request if it fails, whereas you need to do this yourself with the node API. The platform was probably overloaded in that instant, we've been seeing a lot of volume lately.
