### ISSUE TITLE
'orderbook' ws event issues the snapshot as a series of update events

### ISSUE THREAD

**Issue by dutu** [bitfinexcom/bitfinex-api-node#42]
'orderbook' ws event issues the snapshot as a series of update events.
https://github.com/bitfinexcom/bitfinex-api-node/blob/master/ws.js#L276-L308

The API documentation recommends:
1. subscribe to channel with R0 precision
2. receive the raw book snapshot and create your in-memory book structure
3. when price > 0 then you have to add or update the order
4. when price = 0 then you have to delete the order

since the snapshot is issued as a series of 'orderbook' updates it's not possible to know when the "in-memory book structure" has been built and reliable to use.

Can the snapshot be sent as a single event (as also indicated in the API documentation and sent by Bitfinex server), instead of decomposing the snapshot into a series of multiple update events?

**Comment by robertkowalski** [comment]
@dutu as far as I can tell that is the case for the v2 API, were you receive an array of values in the beginning.

for the v1 api, with https://github.com/bitfinexcom/bitfinex-api-node/pull/43 being fixed it should be a detectable by the amount of transmitted values (the length parameter). does that makes sense?

**Comment by robertkowalski** [comment]
@dutu let me double check the client code for the v1 api...

**Comment by robertkowalski** [comment]
looks like an issue in the client code...

**Comment by robertkowalski** [comment]
I see your point now. Probably it makes sense to use an option to opt-in for existing users, to keep backwards compatibility.

**Comment by robertkowalski** [comment]
@prdn can you remember why it is historically that the snapshots (coming from the api as one array)   - are emitted item by item and not as the full array / snapshot?

**Comment by prdn** [comment]
@robertkowalski I really never worked on this library, so hard to tell why. But I think that if we release a macro version we can change it as it make more sense (and emitting a full snapshot makes more sense)

**Comment by robertkowalski** [comment]
ok makes sense. i thought there might be a feature or something i missed.

@dutu #47 will help you i think :)
