### ISSUE TITLE
Request for a release

### ISSUE THREAD

**Issue by sullyfischer** [bitfinexcom/bitfinex-api-node#420]
I had some issues with the latest release, looked for it in the issues section and found a suggestion to install the latest commit instead and it worked. But that makes the package.json messy and produces its own issues. If the master branch is fine by all means, could you please create a release for it? 
Thanks

**Comment by tux-00** [comment]
I agree, the project need more releases.

Le mar. 16 oct. 2018 à 16:53, Sully Fischer <notifications@github.com> a
écrit :
