### ISSUE TITLE
Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by karthik947** [bitfinexcom/bitfinex-api-node#422]
While using websockets subscribeTicker function, receiving below error. Any suggestions on how to stabilize websockets connection ?

{ Error: connect ETIMEDOUT 100.43.134.145:443
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '100.43.134.145',
  port: 443 }

**Comment by f3rno** [comment]
No, it's a network issue. We cannot guard against timeouts, but there is functionality to help cope with them (see `autoReconnect` and `packetWDDelay`)
