### ISSUE TITLE
Does Trailing stop order require "price"?  

### ISSUE THREAD

**Issue by sullyfischer** [bitfinexcom/bitfinex-api-node#426]
This wasn't mentioned, neither on the official docs nor on this repo. When submitting a "TRAILING STOP" order, is the `price` field required?

**Comment by f3rno** [comment]
No, the trail distance is provided via `price_trailing`, you can omit `price`

**Comment by sullyfischer** [comment]
Thank you for your fast respond. Please mention this in the docs as well. Because it's already giving more details for MARKET orders: 
> Not required for market orders

Which is misleading as in like it's only not required for MARKET orders.
