### ISSUE TITLE
How can I unsubscribe candles subscription with Manager

### ISSUE THREAD

**Issue by wierzbix83** [bitfinexcom/bitfinex-api-node#427]
Hi I use WS Manager, I can easily subscribe to observe candles (list of candles in my case)

`candlesToObserve.forEach((value, index) => {
            //subscribe for changes
            this.manager.subscribeCandles(value)
            //add handler to cb on changes
            this.manager.onCandle({ key: value }, (candles) => {
...}}`

I'd like to reload config but it seems that unsubscribe has no effect

`oldCandlesToObserve.forEach((value, index) => {
                this.manager.unsubscribe('candles:'+value)
            })`

Am I doing that correctly?

**Comment by f3rno** [comment]
@wierzbix83 you need to unsubscribe with the channel ID; it is returned on the subscription event:

```js
  _handleSubscribedEvent (msg) {
    this._channelMap[msg.chanId] = msg

    debug('subscribed to %s [%d]', msg.channel, msg.chanId)
    this.emit('subscribed', msg)
  }
```

The manager also emits this event, so you can listen for it with `manager.on('subscribed', ({ chanId, key }) => ...`

Note that the object you get back from the event will also have the key for the candle subscription, I included it in my example above. This will be in the form `'trade:1m:tBTCUSD'`

**Comment by wierzbix83** [comment]
@f3rno seems it doesn't work, anyway it is a bit cumbersome to keep additional key to channel id map, after some diggin it seems that this function returns false and nothing gets unsubscribed:

  hasChannel (chanId) {
    return _includes(Object.keys(this._channelMap), chanId)
  }
![image](https://user-images.githubusercontent.com/44018119/47958337-d765e580-dfc9-11e8-9b4c-4bd5bbca59eb.png)
And nothing is called on unsubscribe - see that channel id is correct

**Comment by f3rno** [comment]
@wierzbix83 you need to pass string channel IDs; this is visible in your screenshot (note that the collection is of strings, but value is a number)

**Comment by wierzbix83** [comment]
@f3rno ok that worked :)
Are you going to make some kind of unsubscribe that will accept the same argument as subscribe operation or this will remain as the only option for some time?

**Comment by f3rno** [comment]
@wierzbix83 that's the way the API does it (by channel ID), so there is no plan to change it. I might add a helper in the future using the local channel map
