### ISSUE TITLE
Cannot read property 'ws' of undefined

### ISSUE THREAD

**Issue by tuloski** [bitfinexcom/bitfinex-api-node#432]
I'm using this code:

```
const bfx = new BFX({
	apiKey: 'xxx',
	apiSecret: 'xxx',

	ws: {
		autoReconnect: true,
		packetWDDelay: 10 * 1000
	}
})

const rest = bfx.rest(2, {
	// options
})

rest.symbolDetails().then(details => {
  const symbols = details.map(d => `t${d.pair.toUpperCase()}`)

  const m = new Manager()

  m.on('error', (err) => {
    debug('error: %s', err)
  })

  m.once('open', () => {

    /*symbols.forEach(symbol => {
      m.subscribeTrades(symbol)
      m.onTrades({ symbol }, (trades) => {
        console.log('recv %d trades on channel %s', trades.length, symbol)
      })
    })*/
	m.subscribeTrades('tBTCUSD');
	m.onTrades((trades) => {
	  console.log('recv %d trades', trades.length)
	})

    setInterval(() => {
    	console.log('num sockets: %d', m.getNumSockets())
    	console.log('socket info: %j', m.getSocketInfo())
    }, 5000)
  })

  m.openSocket()
})
```

And I get:
../lib/ws2_manager.js:369
    s.ws.onTrades({ symbol, cbGID }, cb)
      ^

TypeError: Cannot read property 'ws' of undefined

But the commented code in the snippet above (taken from the examples) which gets all the symbols and subscribes to all trades works. Am I doing something wrong?

How is the correct way to subscribe only to some pairs, and possibly to get the {symbol} filter in the callback.

**Comment by f3rno** [comment]
Hmm, very strange. Does the `ws2_manager` example work for you? It does the same thing internally, and it works for me.

**Comment by tuloski** [comment]
Yes, that works....that's why it's strange.

**Comment by f3rno** [comment]
Does this happen immediately when you run the code, or only after a reconnect event?

**Comment by f3rno** [comment]
Ah, I see the problem: `m.onTrades((trades) => {` needs to be `m.onTrades({ symbol: 'tBTCUSD' }, (trades) => {`

I'll add an error to make this more obvious in the future
