### ISSUE TITLE
Please consider publishing a @types/bfx-api-node-models

### ISSUE THREAD

**Issue by sullyfischer** [bitfinexcom/bitfinex-api-node#436]
Doing so would help a lot those writing typescript. I am personally working on a very high level trading bot which works on Bitfinex:
https://medium.com/@fischersully/introducing-jesse-an-open-source-ai-built-in-crypto-trading-framework-6692907b0f0f

I'm using this library so far, and I could really use a @types/bitfinex-api-node package.

Thanks in advanced.

**Comment by jorisw** [comment]
Howcome you closed this? Did you find a solution? 

I can't use this library in my TS project without using `@ts-ignore` where I initialize the BFX class.

**Comment by ddeath** [comment]
I would say this will not happen anytime soon. It does look like there is no much effort put into this. Also take a look at others repos, they are quite broken. This is too much for one developer to maintain all that code (I assume that Chris is doing all work alone...)

**Comment by f3rno** [comment]
@ddeath how are the other repos quite broken? If you know of issues you should open tickets for them.

This is something which could be done, but as observed by @ddeath I'd be the one to do it and I have my hands full at the moment. I've made a note of it for the future though.

**Comment by sullyfischer** [comment]
I wrote my own implementation in TypeScript in case anyone's looking for an example: 
https://github.com/jesse-ai/jesse/tree/master/core/exchanges/Bitfinex
