### ISSUE TITLE
'orderbook' event emitting / array handling

### ISSUE THREAD

**Issue by robertkowalski** [bitfinexcom/bitfinex-api-node#44]
Right now we geht a snapshot and after that updates.

**Formats:**

snapshot: 

```js
[[[ 1773.8, 1, -0.1 ]]]
```

update:

```js
[ 1775.9, 1, -50 ]
```

**note: both are arrays**

we now process them with the following code:

```js
  _processBookEvent (msg, event) {
    if (Array.isArray(msg[0])) {
      msg[0].forEach((bookLevel) => {
        debug('Emitting orderbook, %s, %j', event.symbol, bookLevel)
        this.emit('orderbook', event.symbol, bookLevel)
      })
    } else if (msg[0] === 'hb') { // HeatBeart
      debug('Received HeatBeart in %s book channel', event.symbol)
    } else if (msg.length > 2) {
      debug('Emitting orderbook, %s, %j', event.symbol, msg)
      this.emit('orderbook', event.symbol, msg)
    }
  }
```

As both are arrays, we are always process the data with the forEach loop. The 

```js
else if (msg.length > 2)
``` 

branch is never called and dead code.

That leads me to the assumption that we have a bug here, as the emitted data for updates look like this:

```
1770
0
-1
```

which is not very user friendly and leads to errors as soon as multiple orderbooks are subscribed, as each number is emitted alone.

Proposal:

Emit snapshots as an array, and emit other data as tuples / lists to keep them in consistent relation.

**Comment by prdn** [comment]
@robertkowalski sounds good to me
