### ISSUE TITLE
Book not updated on trades

### ISSUE THREAD

**Issue by tuloski** [bitfinexcom/bitfinex-api-node#440]
I don't know if it is supposed to be like this, but when I receive a trade event on a pair, I don't get the update on the book on the same pair.

I'm using the manager with "subscribeOrderBook".

**Comment by tuloski** [comment]
Example.
I have the initial orderbook on pair MGOETH (only the bid):
----------- BOOK MGOETH -------------
[0.005504,1,120.7548] [0.0055433,1,-733.34310142]
[0.005418,1,120] [0.005544,1,-180]
[0.005382,1,101.6853] [0.00555,1,-637.8564653]

Then a trade occurs (at 54 seconds and 770 milliseconds):
20:16:54:770 Trades MGOETH: [{"id":321617015,"mts":1544296614681,"amount":-120.75373703,"price":0.005504}]
The trade removed the first offer completely.

And the update on the book is only at time 55 sec 11ms (probably because other offers changed in the book):
----------- BOOK MGOETH -------------
[0.005418,1,120] [0.0055041,1,-100]
[0.005382,1,101.6853] [0.0055433,1,-733.34310142]
[0.005346,1,109.8548] [0.005544,1,-180]

**Comment by f3rno** [comment]
Yes this is normal, the book updates are sent periodically, sometimes representing multiple trades during times of high activity. You did receive the update, only ~1 second later

**Comment by tuloski** [comment]
Is this bitfinex or api side?
If on API side why not emitting a book also every trade?

**Comment by f3rno** [comment]
API-side; there are simply too many trades to also broadcast book changes after each one. If you want finer-grain updates, subscribe to a raw book (precision `R0`) to receive a price level for each order.

**Comment by f3rno** [comment]
The default subscription is for `P0`; you can switch it to `R0` with no other changes, but be aware the raw book has a different format (order ID instead of price level)

**Comment by tuloski** [comment]
@f3rno and will using R0 still build the book object as with "manageOrderBooks: true", and "transform: true"?

**Comment by tuloski** [comment]
Also I don't understant why are you mentioning R0? Isn't it the price aggregation level?
Isn't F0 the param for real-time? I'm a bit confused.

From the docs there are Px and Fx for precision and frequency of Order books.
Then there is param R0 for raw orderbook (but it is not described what R0 means...).

Isn't using P0 and F0 give a real time book with the biggest precision?

**Comment by f3rno** [comment]
`R0` gives you the raw order book, where each entry is an individual order, whereas `Px` gives you price level books where each entry is one price level. `R0` is as precise as it gets. Everything else stays the same (`manageOrderBooks`/etc), but be aware the format is different.

**Comment by tuloski** [comment]
We tried with R0. It works better but not perfectly, but I think it's a server issue.
In the following a log:

11:31:15:917  ----------- BOOK BTCUSD -------------
11:31:15:917  [20659145246,4057.5,50.97396551] [20659279605,4057.5330598,-0.55977736]
11:31:15:917  [20659230647,4057.5,0.6323089] [20659209398,4057.6,-0.72807268]
11:31:15:917  [20659277691,4057.5,0.44] [20659217752,4057.6,-0.15387832]
**11:31:16:023**  Trades BTCUSD: [{"id":325942905,"mts":1545474675950,"amount":-0.06149407,"price":4057.5}]
11:31:16:288  ----------- BOOK BTCUSD -------------
11:31:16:288  [20659145246,4057.5,50.97396551] [20659279605,4057.5330598,-0.55977736]
11:31:16:288  [20659230647,4057.5,0.6323089] [20659209398,4057.6,-0.72807268]
11:31:16:288  [20659277691,4057.5,0.44] [20659217752,4057.6,-0.15387832]
11:31:16:288  ----------- BOOK BTCUSD -------------
11:31:16:288  [20659145246,4057.5,50.97396551] [20659279605,4057.5330598,-0.55977736]
11:31:16:288  [20659230647,4057.5,0.6323089] [20659209398,4057.6,-0.72807268]
11:31:16:288  [20659277691,4057.5,0.44] [20659217752,4057.6,-0.15387832]
11:31:16:288  ----------- BOOK BTCUSD -------------
11:31:16:288  [20659145246,4057.5,50.97396551] [20659279605,4057.5330598,-0.55977736]
11:31:16:288  [20659230647,4057.5,0.6323089] [20659273974,4057.6,-0.25646451]
11:31:16:289  [20659277691,4057.5,0.44] [20659217206,4057.6,-0.0635]
11:31:16:289  ----------- BOOK BTCUSD -------------
**11:31:16:289**  [20659145246,4057.5,50.91247144] [20659279605,4057.5330598,-0.55977736]
11:31:16:289  [20659230647,4057.5,0.6323089] [20659273974,4057.6,-0.25646451]
11:31:16:289  [20659277691,4057.5,0.44] [20659217206,4057.6,-0.0635]

As you can see the trade happens at 023 ms and the book is finally updated at 289ms, with 3 books not updated in between. There is always a delay of 200-300ms between the trade and the book update.
