### ISSUE TITLE
Getting issues and errors with websockets after Bitfinex update

### ISSUE THREAD

**Issue by jamason88** [bitfinexcom/bitfinex-api-node#449]
Hi, 
Ive started to get issues with the websockets feed since bitfinex have upgraded their servers.
I am using version 2 websockets and the current version 2.04.
Ever since they upgraded their servers the other day, i have started getting blank errors irregularly every 5-10 minutes. The feed also freezes and just keeps returning the same value unless i reset it every 2 minutes.

Not sure its an error from their end, but thought id ask anyways

Thank you

**Comment by f3rno** [comment]
@jamason88 what do you mean by blank errors? Can you post an example packet log?

**Comment by jamason88** [comment]
When catching errors with:  

ws.on('error', (err) => console.log(err))

It was only returning: {}

When this error would happen, being subscribed to ticker would keep returning the same value indefinitely.

It appears it was a server migration issue as i have stopped receiving them now. Closing the issue

Thank you
