### ISSUE TITLE
maximum length (depth) of raw orderbook (ws)

### ISSUE THREAD

**Issue by dutu** [bitfinexcom/bitfinex-api-node#45]
Hi,
Would you please let me know what is the maximum length (depth) of raw orderbook that can be received on WebSocket.
Have tried a few values higher than 100, but I'm getting the error "length: invalid".

Thank you!

**Comment by robertkowalski** [comment]
from reading the docs it can be 25 *or* 100 

i can't look into the server code, so i have to take the docs here as reference. i can try to find out though

**Comment by dutu** [comment]
OK, thank you. I have also opened a ticket with Bitfinex support

**Comment by dutu** [comment]
response from Bitfinex support:

> LENGTH	string	Number of price points ("25", "100") [default="25"]
> currently the only two acceptable values are these.
>

**Comment by dqian** [comment]
250 seems to work

**Comment by nkv42** [comment]
Still not enough
