### ISSUE TITLE
Incomplete order status messages returned from rest2 api

### ISSUE THREAD

**Issue by QuentinFAIDIDE** [bitfinexcom/bitfinex-api-node#452]
Hello,
Lately I've been doing a lot of testing, and I so downloaded the last 50 orders closing status to setup a test unit for an order filling status parsing functions, only to see that long order status were incomplete. I used the Rest 2 object, so I'm now wondering, either this api can't receive big message, either the problem is on bitfinex server side.
This is an example of a status message that has been damaged:
EXECUTED @ 417.79(-2.71): was PARTIALLY FILLED @ 418.47(-4.63), PARTIALLY FILLED @ 418.4(-0.1), PARTIALLY FILLED @ 418.3(-0.1), PARTIALLY FILLED @ 418.2(-0.1), PARTIALLY FILLED @ 418.1(-0.1), PARTIALLY FILLED @ 418.05(-0.1), PARTIALLY FILLED @ 418.0(
You can see the last partial fill report is missing volume and parenthesis:  "PARTIALLY FILLED @ 418.0("
I'm only dev with API Keys so I can't go and check on the website if there are complete reports there, is anyone experiencing the same problem ?
btw here's a script to get order status history in case you want to check if that reproduces on your servers:
```javascript
const BFX = require('bitfinex-api-node');
const {Order} = require('bitfinex-api-node/lib/models');
// bitfinex api instance creation 
const bfx = new BFX({
  apiKey: YOUR_API_KEY
  apiSecret: YOUR_API_SECRET,
  ws: {
    autoReconnect: true,
    seqAudit: false,
  },
});

// rest inteface object
const rest = bfx.rest(2, { transform: true })
const pair = 'tBTCUSD'
const symbol = pair[0] === 't' ? pair : `t${pair}`

// TODO: natural lang start/end query args (a library must exist)
const START = Date.now() - (30 * 24 * 60 * 60 * 1000 * 1000)
const END = Date.now()
const LIMIT = 50;

rest.orderHistory(symbol, START, END, LIMIT).then(orders => {
  let o

  for (let i = 0; i < orders.length; i += 1) {
    o = orders[i]
    console.log(o.status);
  }
}).catch(err => {
  debug('error: %j', err)
})
```

**Comment by QuentinFAIDIDE** [comment]
We can still approach matching price with relatively low error rate by using the first 250 characters from the incomplete fill message, and I don't think it will be fixed soon, so either we make the switch to FIX protocol to have different data structure returned (painful and costly), or we go with the averaging "wet finger" approach 🤷

**Comment by f3rno** [comment]
We will continue to enforce the 250 chart limit on order status strings for the time being. I will update this issue in the future if the limit changes.
