### ISSUE TITLE
v2 api trades/hist endpoint returns only 2018 & 2019 trades

### ISSUE THREAD

**Issue by MaxPovver** [bitfinexcom/bitfinex-api-node#454]
I've checked both trades/hist & trades/BTC/hist formats, both return  only trades starting from 01/01/2018. While for the same account v1 endpoint /mytrades returns all user's trades

**Comment by f3rno** [comment]
Try adding `{ _bfx: 1 }` to the request payload, it should enable you to retrieve data prior to 2018.
