### ISSUE TITLE
Is there a way to map symbols?

### ISSUE THREAD

**Issue by npomfret** [bitfinexcom/bitfinex-api-node#462]
The reports UI maps my old (pre-fork) tBCHUSD trades and displays them as BCH/USD.  The same goes for new tBABUSD trades which are also mapped to BCH/USD.

Is there an API call that I can use to provide this mapping?

**Comment by f3rno** [comment]
Duplicate of https://github.com/bitfinexcom/bfx-api-node-rest/issues/19
