### ISSUE TITLE
Restapi V2 Claim positions and Cancel Position apis missing

### ISSUE THREAD

**Issue by g666nz** [bitfinexcom/bitfinex-api-node#463]
HI I was wondering if there is an API for closing a position and claiming a position api or websocket calls.

**Comment by f3rno** [comment]
Yep; both calls are available on RESTv2 (pass-throughs from RESTv1) as: `claimPosition` and `closePosition`

Source: https://github.com/bitfinexcom/bfx-api-node-rest/blob/master/lib/rest2.js#L1011

**Comment by anwfr** [comment]
Opening opposite order sometimes does not properly close the position, leaving a zero-sized position opened.
Why not adding close to WSv2?
