### ISSUE TITLE
How to create a new order with TIF set

### ISSUE THREAD

**Issue by wierzbix83** [bitfinexcom/bitfinex-api-node#466]
Seems that tif field is ignored

I applied code similar to examples but tif field has no effect on the placed order

`//https://docs.bitfinex.com/v2/reference#ws-input-order-new
                msg = {
                    //gid: msg.gid,
                    cid: Date.now(),
                    symbol: 'tBTCUSD',
                    amount: 0.1,
                    type: Order.type.LIMIT, //MARKET, EXCHANGE MARKET, LIMIT, EXCHANGE LIMIT, STOP, EXCHANGE STOP, TRAILING STOP, EXCHANGE TRAILING STOP, FOK, EXCHANGE FOK, STOP LIMIT, EXCHANGE STOP LIMIT, IOC, EXCHANGE IOC
                    price: 1,
                    //price_trailing: null,
                    //price_aux_limit: null,
                    //price_oco_stop: null,
                    //flags: 1024
                    tif: "2020-01-01 10:45:23" //Time-In-Force: datetime for automatic order cancellation (ie. 2020-01-01 10:45:23) )
                }

               
                // Build new order
                const o = new Order(msg, this.ws)

                // Enable automatic updates
                o.registerListeners()
                o.on('update', () => {
                    log.debug("Order updated " + JSON.stringify(o.toJS()))
                })
                o.on('close', () => {
                    log.debug("Order closed " + JSON.stringify(o.toJS()))
                    o.removeListeners()
                })
                o.on('open', () => {
                    log.debug("Order opened " + JSON.stringify(o.toJS()))
                })

                log.info("Submitting order " + JSON.stringify(o.toJS()))
                return o.submit().then((order) => {
                    log.debug("Got submit confirmation for order " + JSON.stringify(order.toJS()))
                    return order.toJS()
                }).catch((err) => {
                    log.error(err)
                    throw err
                })
                break`

Is there a way to utilize TIF with node.js API?

**Comment by f3rno** [comment]
Fixed by https://github.com/bitfinexcom/bfx-api-node-models/pull/16

You can now pass the `tif` field to the `Order` model constructor; note that the field returned from the API is `mtsTIF` and is in milliseconds, unlike `tif` (date string)

**Comment by wierzbix83** [comment]
thanks, fixed :)
