### ISSUE TITLE
Add FAQ: The reason for the error with code 10100

### ISSUE THREAD

**Issue by rodsher** [bitfinexcom/bitfinex-api-node#470]
Hi!
I noticed that `bitfinex-api-node` package users sometimes have questions about the error with code 10100 when they use API like this:
```js
const bfx = new BFX({
  ws: {
    autoReconnect: true,
    ...
  },
});

ws.on('open', () => {
   ws.auth()
})
```

I think it is a good idea to place problem-solving in the FAQ in README. May I do pull request that add additional item in FAQ?

Best regards,
Max

**Comment by MowgliB** [comment]
I would argue that this is the purpose of the API documentation which is the very first link in the documentation. The error codes are all outlined in the [Abbreviation Glossary](https://docs.bitfinex.com/v2/docs/abbreviations-glossary).

**Comment by f3rno** [comment]
@MowgliB correct, closing.
@rodsher see #479 for follow-up
