### ISSUE TITLE
How can I request onOrderSnapshot? (ws2)

### ISSUE THREAD

**Issue by vsly-ru** [bitfinexcom/bitfinex-api-node#474]
There's a function (listener) `ws2.onOrderSnapshot({}, (snapshot) => {...})'` (but it only fires when I connect and authorize) and `ws2.onOrderNew; onOrderUpdate and onOrderClose`.
They _should_ notify me anytime something happened with any of my orders (or new one), but what if, for some reason(i.e. internet problems), I didn't receive one of this onOrderNew/Update/Close messages and it was critical? 

I want to periodically request snapshots to make sure my information is up to date. 
It would be perfect if there was a method like requestOrderSnapshot(); But I can not find any. 
So how can I request it?

**Comment by MowgliB** [comment]
I don't think this is possible. The idea should be that you store your initial snapshot from when you open the web socket connection and then update it as you receive new data. That is how all things web socket work. If you disconnect from the WS server (and miss out on any new data), you should get a new snapshot upon reestablishing your connection.

If you want a "snapshot" of your open orders periodically, you should be using the REST API. If I understand you correctly, the `resTv2.activeOrders(cb)` ([reference link](https://github.com/bitfinexcom/bitfinex-api-node/blob/master/doc/rest2.md#RESTv2+activeOrders)) should do what you're after.
