### ISSUE TITLE
Web Socket works for several hours before Node outputs "aborted" and closes app

### ISSUE THREAD

**Issue by SimpleProgrammingAU** [bitfinexcom/bitfinex-api-node#475]
I have been performing a few tests to make sure I have reliable data coming in from the web socket connection. After a few hours, I keep running into the same problem.

No errors are thrown, just a single word outputted to the console:

    aborted

At this stage, all I am doing is subscribing to the Ticker and Order Book data streams and monitoring them. At first, I thought it might be an issue because I am not interacting with the server, so I started sending `ping` messages to see if that would resolve the issue. It did not. I have been storing the data received in a SQLite database file and appear to be receiving good data for the period I am connected.

Is there any reason why my app would end abruptly without encountering any other errors? Is this an issue caused by Node.js itself? I haven't been able to find anything online to suggest that, yet.

**Update**: I have been testing the app on my high-spec desktop and it has been running for almost 12 hours without an issue. The issue has only occurred so far on my Raspberry Pi running Raspbian. Unsure what is causing the issue.

**Another Update**: Follow up question, there are three different ways Node.js can fire the `aborted` event according to the docs: `Http2Stream`, `http.IncomingMessage`, and `http2.Http2ServerRequest`. I will make an attempt to listen to each of these and see if any of them are fired. Can someone tell me which of these modules would be used in the Bitfinex API?

**Comment by f3rno** [comment]
@MowgliB any update?

**Comment by MowgliB** [comment]
I haven't been able to work out what's causing the `aborted` message to occur. Would love it if someone could guide me where to look.

**Comment by f3rno** [comment]
@MowgliB can you provide the output of `ulimit -a` on your rpi? It looks like node is running out of (some) resources.

**Comment by MowgliB** [comment]
I will do that tonight and report back the results.
