### ISSUE TITLE
wss://api-pub.bitfinex.com/ws/2 errors

### ISSUE THREAD

**Issue by tadeuszwojcik** [bitfinexcom/bitfinex-api-node#480]
Looking at commits I've noticed that your are preparing for decreased subscribe limits via single connection (from 250 to 30), but it's not mentioned anywhere in changelog but when connecting via `wss://api-pub.bitfinex.com/ws/2`  that new limit already applies without any prior official heads up. Is `wss://api-pub.bitfinex.com/ws/2` expected to be experimental/unstable endpoint? I've noticed it's mentioned in docs hence used it.

**Comment by f3rno** [comment]
This has been added to the changelog (limit is 25.) Apologies for the delayed update to this lib.
