### ISSUE TITLE
how to create a market order

### ISSUE THREAD

**Issue by yourmykola** [bitfinexcom/bitfinex-api-node#501]
#### Issue type
- [ ] bug
- [ ] missing functionality
- [ ] performance
- [ ] feature request
- [X] question

#### Brief description
I am trying to create an order to close a position in trading, so I use 
price = 0;
this.bitfinex.new_order (this.pair, 0.06 ,  price ,  this.name.toLowerCase (),  buy,  "market",)
but get 
#### Steps to reproduce
but I get the error "Order price must be positive". If I want to create a market order (sell \ buy at the market price), what price do I need to specify in the amunt parameter. If I have to make a request to get the current price, what is the difference between the types of orders "market" and "limit". 

##### Additional Notes:
I want to use the type of market to be sure that I have closed all of the entire position, maybe there is another function for this and I'm digging in the wrong place?

**Comment by JacobPlaster** [comment]
Hi @yourmykola I will need to see some more of your code in order to help.

For info on a bitfinex market order see: https://support.bitfinex.com/hc/en-us/articles/115003503769-Market-Order
For info on a bitfinex limit order see: https://support.bitfinex.com/hc/en-us/articles/115003506105-Limit-Order

**Comment by yourmykola** [comment]
Unfortunately, I can’t throw off the code, because it is part of a large project.
I realized that you can pass any positive number to the price parameter, if the type of order means "market", the exchange itself will choose the price. this is:

price = 1000;
this.bitfinex.new_order (this.pair, 0.06, price, this.name.toLowerCase (), purchase, “market”)

This works when closing a position, when I have a short position, that is, when I buy. But when I try to close a long position in the same way, the order is not executed immediately, and despite the fact that I specified the quantity parameter after the order is executed, a small amount of cryptocurrency remains, for example, 0.0000016 in a long position. ,
How to close positions correctly to completely close them
