### ISSUE TITLE
How to get fee percent for trades from api?

### ISSUE THREAD

**Issue by MaxPovver** [bitfinexcom/bitfinex-api-node#510]
#### Issue type
- [x] question

#### Description
Right now there is no easy way to find out if trade was made on margin wallet or on exchange wallet. 

However, I can clearly see that in https://report.bitfinex.com/trades/ there is a "Fee percent" field that is returned ONLY for margin trades, so it could be used as a margin trades flag. 
![image](https://user-images.githubusercontent.com/9439263/72848565-8cf38600-3cad-11ea-8542-50025784a801.png)

But it does not help because v2 api trades endpoint https://api.bitfinex.com/v2/auth/r/trades/*Symbol*/hist does not return this field in its response. Is there any way to get this fee field? And if not, is there any good way to find out if trade was margin or not?

**Comment by JacobPlaster** [comment]
@MaxPovver I think a member of our customer support team may have solved this query for you. But just for the sake of other people stumbling across this, you can get this info using the v1 account summary endpoint:

https://docs.bitfinex.com/v1/reference#rest-auth-summary
