### ISSUE TITLE
Why the big version bump?

### ISSUE THREAD

**Issue by npomfret** [bitfinexcom/bitfinex-api-node#512]
I can't find release notes - are there any?  Is something new incompatible with version 3.x?

**Comment by JacobPlaster** [comment]
Hi yes, the major change was the format of the data returned from the v2 Rest functions. See PR https://github.com/bitfinexcom/bfx-api-node-rest/pull/42.

I agree, the changelog update probably shouldve been more descriptive (my bad), but it was there:
```
4.0.0
- include bfx-api-node-rest takeNotification hotfix
```

**Comment by JacobPlaster** [comment]
P.S I updated the changelog entry to this:

```
4.0.0
- include bfx-api-node-rest takeNotification hotfix.
  This pull request changed the schema of data returned from the v2
  REST functions. See pr https://github.com/bitfinexcom/bfx-api-node-rest/pull/42
  for more info
```

Thanks for bringing it to our attention
