### ISSUE TITLE
[Question] How to get active orders and bind to their events when starting a new connection. 

### ISSUE THREAD

**Issue by jcbit** [bitfinexcom/bitfinex-api-node#514]
#### Issue type
- [X] Question
#### Brief description
After I close my app when I reopen I want to be able to get all active orders I left and bind events to them go handle them (on close, etc). I tried to do ws.onOrderSnapshot like on the cancel all orders example but it never gets called. I authenticate and can trade but the ws.onOrderSnapshot event never gets triggered. Any ideas? 

#### Steps to reproduce
-

##### Additional Notes:
- First update: Seems I do get an order snapshot if I set it up before I open the ws. But after I am authenticated and all if I want to pull a new snapshot how do I do it?

**Comment by f3rno** [comment]
Can you share a minimal snippet that reproduces this for you?

**Comment by f3rno** [comment]
Based on your update, this is expected behavior. The snapshot is sent along with a series of other data payloads after authentication that are intended to be used for initializing state, and needs to be updated locally afterwards using incoming order change (`on`, `ou`, `oc`) packets.
