### ISSUE TITLE
Do onMaintenanceStart() and onMaintenanceEnd() actually work?

### ISSUE THREAD

**Issue by JacobBruce** [bitfinexcom/bitfinex-api-node#528]
I used the following code to setup a websocket connection, but I've noticed that during the last couple of maintenance periods the callback functions for onMaintenanceStart() and onMaintenanceEnd() never seem to get called because there's nothing in the logs. The error callback function however is triggered when the Bitfinex server goes into maintenance mode, producing error codes such as 408, 503, and 429. Am I setting things up correctly or is it a bug? Should I maybe not use autoReconnect:true?

```
const BFX = require('bitfinex-api-node');
var bfx = null;
var bfx_ws = null;

function StartFunc() {

	bfx = new BFX({
		apiKey: '...',
		apiSecret: '...',

		ws: {
			autoReconnect: true,
			transform: true
		}
	});

	bfx_ws = bfx.ws(2);

	bfx_ws.on('open', () => {
		console.log('bfx connection opened');
		if (!bfx_ws.isAuthenticated()) bfx_ws.auth();
	});
	
	bfx_ws.on('close', () => {
		console.log('bfx connection closed');
	});
	
	bfx_ws.on('error', (err) => {
		console.error('bfx ws error', err);
	});
	
	bfx_ws.once('auth', () => {
		console.log('bfx api key authenticated');

		bfx_ws.onMaintenanceStart(() => {
			console.log('bfx info: maintenance period started');
		});

		bfx_ws.onMaintenanceEnd(() => {
			console.log('bfx info: maintenance period ended');
		});

		bfx_ws.onServerRestart(() => {
			console.log('bfx info: server has restarted');
		});
	});

	bfx_ws.open();
}
```

**Comment by f3rno** [comment]
It is likely that the connection is being reset, but you should still be seeing the maintenance messages. Can you post the relevant section of your log? I added a quick unit test and it works as expected:

```js
  describe('onMaintenanceStart', () => {
    it('is called when receiving a 20060 info code', async () => {
      ws = createTestWSv2Instance()
      wss = new MockWSv2Server()

      await ws.open()

      return new Promise((resolve) => {
        ws.onMaintenanceStart(() => resolve())
        wss.send({
          event: 'info',
          code: '20060'
        })
      })
    })
  })
```

**Comment by JacobBruce** [comment]
Unfortunately I deleted most of the logs because it was just repeating the same 429 error. I think it started with 503 errors then changed to 429 error. However I think this is the log for when a previous maintenance period started. I don't think I was using onServerRestart at that time. I have other code which uses the websocket connection to get candle data every few minutes, not sure if that's what triggered the websocket error though. It will only attempt to get the candle data when bfx_ws.isOpen() is set to true, but I'm guessing it can remain open in maintenance periods?

```
bfx connection closed
bfx websocket error Error: unexpected server response (408)
    at ClientRequest._req.on (/.../node_modules/ws/lib/WebSocket.js:653:21)
    at ClientRequest.emit (events.js:198:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:94:17)
```

**Comment by JacobPlaster** [comment]
Closing since we will need more logs to highlight the issue.
