### ISSUE TITLE
Q: max value of cid when submitting new order

### ISSUE THREAD

**Issue by dutu** [bitfinexcom/bitfinex-api-node#532]
Would you please clarify what is the max value of `cid` field when submitting a new order?

Note: For WebSocket [New Order](https://docs.bitfinex.com/reference#ws-auth-input-order-new) documentation says `cid` is int45, but for rest API [Submit Order](https://docs.bitfinex.com/reference#rest-auth-submit-order) documentation says it should be int32.

**Comment by JacobPlaster** [comment]
Hi @dutu, websocket and rest requests are initially processed by a layer of nodejs edger servers. So you the max value for the cid would be the Javascript `MAX_SAFE_INTEGER` value.
