### ISSUE TITLE
Q: meta field for `on` request

### ISSUE THREAD

**Issue by dutu** [bitfinexcom/bitfinex-api-node#533]
I have noted that, when including `meta` object in `on` request, the object is passed back in `on-req` notification.
Can you confirm this as a reliable/usable method of including an additional field (for example `cidStr`) for matching `on-req` notification to the `on` request?

Example :
```js
meta = {
  aff_code: "KCtNtc_O",
  cidStr: "adcd123"
}
```

**Comment by JacobPlaster** [comment]
Hi @dutu appologies for the late reply. Yes the meta has been added for that use case, however it is currently only being used internally.
