### ISSUE TITLE
module should follow semver

### ISSUE THREAD

**Issue by dutu** [bitfinexcom/bitfinex-api-node#57]
although module is not published on npm, it needs to step up major release since it introduces API which changes which break backwards compatibility

https://docs.npmjs.com/getting-started/semantic-versioning

**Comment by robertkowalski** [comment]
yep, agreed!

we are already preparing 1.0.0:
https://github.com/bitfinexcom/bitfinex-api-node#version-100-breaking-changes

**Comment by robertkowalski** [comment]
we just released 1.0.0
