### ISSUE TITLE
REST post only order

### ISSUE THREAD

**Issue by nedievas** [bitfinexcom/bitfinex-api-node#63]
Hi. Is it possible to send 'is_postonly: true' via this REST API?

**Comment by prdn** [comment]
yes, you should be able to

**Comment by nedievas** [comment]
Would you be so kind and show me example? 
```
client.new_order('btcusd', '0.1', '0.1', 'bitfinex', 'buy', 'exchange limit', false, /*is_postonly,*/ function (err, body) {
        if (err) return cb(err)
        cb(null, body)
      }) 
```

**Comment by robertkowalski** [comment]
hi @nedievas,

i'm going to implement this next week.

for today i can just recommend to use `make_request` which is wrapped by `new_order `, so you can continue to work and are not blocked.

**Example:**

```js
const params = {
    symbol,
    amount,
    price,
    exchange,
    side,
    type,
    is_hidden,
    is_postonly
  }

client.make_request('order/new', params, cb)
```

Code: https://github.com/bitfinexcom/bitfinex-api-node/blob/dc183255335c3dfdc9fa608325de1f41a0b41a8b/rest.js#L182-L199

**Comment by nedievas** [comment]
Hi @robertkowalski,
Thank you! I'll try your suggestion.

**Comment by nedievas** [comment]
Does anybody know the error message when is_postonly=true order is not able to execute?
Like when it is not enough of balance, the message would be "Error: Invalid order: not enough exchange balance...."
