### ISSUE TITLE
Error: unexpected server response (429)

### ISSUE THREAD

**Issue by glaucoheitor** [bitfinexcom/bitfinex-api-node#81]
From time to time, I am getting a 429 error from WS even making a REST request.

That also crash the script.

`events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: unexpected server response (429)
    at ClientRequest._req.on (/home/cards4magic/public_html/soredigitmedia/btc/node/node_modules/bitfinex-api-node/node_modules/ws/lib/WebSocket.js:649:26)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:563:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:452:20)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:250:12)
    at readableAddChunk (_stream_readable.js:237:11)
    at TLSSocket.Readable.push (_stream_readable.js:195:10)
    at TLSWrap.onread (net.js:586:20)`

Any ideia on why this is happenning and what I can do to mitigate it or even make it catch this error and don't crash the script?

**Comment by robertkowalski** [comment]
hi @glaucoheitor, thanks for reporting!

429 is a "too many requests" error. You raise a good point which is an issue. The current entry point usually opens a new websocket. You can workaround the issue right now with passing `autoOpen: false` as option:

**Example:** 

```js
const bfx = new BFX('dummy', 'dummy', { version: 2, autoOpen: false })
```

Please note that this is not officially documented and may get removed in later versions. 

In fact there is a more elegant solution planned, which would be a **breaking** change. As user of our API client **your feedback would be really valuable**: https://github.com/bitfinexcom/bitfinex-api-node/issues/41

**Comment by robertkowalski** [comment]
abandoned issue -- closing

**Comment by glaucoheitor** [comment]
This should be addressed so we dont get that much 429 errors.
Even using autoOpen: false it didnt resolved 100%.

I am using a time counter to not send more than one request every 2s.

**Comment by ThePlenkov** [comment]
@robertkowalski Don't you know by some chance what is exactly the server logic?

First I faced errors when I called several requests instantly..  Now I made 2sec delay but still have an issue with the last request:
node --inspect-brk=42861 simulator.js 
Debugger listening on ws://127.0.0.1:42861/d746e658-d7eb-4a69-a040-e133f9ce51b7
tBTCUSD simulation started
API call: /candles/trade:3h:tBTCUSD/hist
API call: /candles/trade:1h:tBTCUSD/hist?start=1516665600000&sort=1&size=1000
API call: /candles/trade:30m:tBTCUSD/hist?start=1516665600000&sort=1&size=1000
API call: /candles/trade:15m:tBTCUSD/hist?start=1516665600000&sort=1&size=1000
API call: /candles/trade:5m:tBTCUSD/hist?start=1516665600000&sort=1&size=1000
API call: /candles/trade:5m:tBTCUSD/hist?start=1516708800000&sort=1&size=1000
API call: /candles/trade:5m:tBTCUSD/hist?start=1516752000000&sort=1&size=1000
API call: /candles/trade:15m:tBTCUSD/hist?start=1516773600000&sort=1&size=1000
API call: /candles/trade:5m:tBTCUSD/hist?start=1516795200000&sort=1&size=1000
API call: /candles/trade:5m:tBTCUSD/hist?start=1516838400000&sort=1&size=1000
API call: /candles/trade:30m:tBTCUSD/hist?start=1516881600000&sort=1&size=1000
API call: /candles/trade:15m:tBTCUSD/hist?start=1516881600000&sort=1&size=1000
API call: /candles/trade:5m:tBTCUSD/hist?start=1516881600000&sort=1&size=1000
API call: /candles/trade:5m:tBTCUSD/hist?start=1516924800000&sort=1&size=1000
API call: /candles/trade:5m:tBTCUSD/hist?start=1516968000000&sort=1&size=1000
API call: /candles/trade:15m:tBTCUSD/hist?start=1516989600000&sort=1&size=1000
API call: /candles/trade:5m:tBTCUSD/hist?start=1517011200000&sort=1&size=1000
API call: /candles/trade:5m:tBTCUSD/hist?start=1517054400000&sort=1&size=1000

It is always 10th request. How many seconds(minutes) should I wait to avoid this?

Thank you!

**Comment by ThePlenkov** [comment]
I noticed that I made a type. limit is a correct URL.
