### ISSUE TITLE
orderbook not sorted properly

### ISSUE THREAD

**Issue by TestniTester** [bitfinexcom/bitfinex-api-node#83]
example:
'2734.4': { PRICE: 2734.4, COUNT: 2, AMOUNT: -10,5990971},
'2734.8': { PRICE: 2734.8, COUNT: 1, AMOUNT: -0,11},
'2734.3': { PRICE: 2734.3, COUNT: 1, AMOUNT: -4.260452},
'2736.9': { PRICE: 2736.9, COUNT: 1, AMOUNT: -0,01068},

same sort error on bids/asks

**Comment by robertkowalski** [comment]
Hello and thanks for reporting!

I'm not sure if I can follow, can you elaborate please what the error is and how it happens for you? 

Thank you in advance!

**Comment by TestniTester** [comment]
if you open orderbook.js (examples)
the orders in orderbook array are not properly sorted...
if you look up my example, all orders in ALL orderbooks should be sorted by price....
BIDS descending, ASKS ascending...
right?
her...they are mot properly sorted
2734,4
2734,8
2734,3
2736,9
should acualy be
2734,3
2734,4
2734,8
2736,9
right?

**Comment by robertkowalski** [comment]
You raise a good point.

In JavaScript just plain Arrays guarantee sorting order, the example does not provide a sorted orderbook and uses a hashmap like structure for fast inserts and deletes.

It's easy to sort the data with `Object.keys` to get an array from each side and use `.sort` to make it sorted ascending or descending. 

I'm busy with some other fixes right now, but I opened #84
