### ISSUE TITLE
Provide an example to sort the orderbook

### ISSUE THREAD

**Issue by robertkowalski** [bitfinexcom/bitfinex-api-node#84]
From https://github.com/bitfinexcom/bitfinex-api-node/issues/83:

It's not obvious that the data in the Hashmap is not sorted by price and that you need to create some kind of sorted lists in order to have a sorted list with the orderbook values.

Provide an additional method that takes the current data and merges it back into a list.

**Comment by sjashwin** [comment]
Can I complete this?
