### ISSUE TITLE
ws public : 'candles' -- Any plan to implement it ?

### ISSUE THREAD

**Issue by censix** [bitfinexcom/bitfinex-api-node#86]
Very lean implementation. Do you have a plan to implement the 'candles' of the public ws ?  It is part of the full v2 api.

https://docs.bitfinex.com/v2/reference#ws-public-candle

**Comment by robertkowalski** [comment]
its not in the backlog, but happy to accept contributions!

**Comment by robertkowalski** [comment]
@Tetradeca are you happy to submit a PR containing your candles addition? That would be great!

**Comment by Tetradeca** [comment]
Sure I can do that

**Comment by lapwat** [comment]
hi, line 113 you forgot event as second parameter

**Comment by Tetradeca** [comment]
Ah indeed, thanks!

**Comment by censix** [comment]
Cool !

**Comment by lapwat** [comment]
Still got this error, not sure where it comes from.
`TypeError: Cannot read property 'fundingCurrencies' of undefined`

**Comment by Tetradeca** [comment]
Ah yes, that's why I was not passing the event actually. I fixed it correctly on another branch I made but it had a very different structure, let me see what I can do.

**Comment by lapwat** [comment]
Thank you dude

**Comment by Tetradeca** [comment]
Actually it might have been simpler than that, can you try updating with my latest commit?

**Comment by lapwat** [comment]
I have already implemented my workaround and it works. I will try your version when I need candle multipairs.
If your version works, maybe you could try submitting a push request ?

**Comment by Tetradeca** [comment]
It's already proposed as a PR, but I think the repo owner is a bit overwhelmed elsewhere.

**Comment by robertkowalski** [comment]
Hey folks,

thank you for being patient, I was swamped with other work.

I just merged the candles work @Tetradeca provided :)

**Comment by lapwat** [comment]
event.symbol is still undefined
