### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by danielbjornadal** [bitfinexcom/bitfinex-api-node#87]
I cant find anything in the documentation about how to submit or cancel orders?
Should provide some examples.

```
  bws.on('oc', (id) => {
    // ???
  }); 
```

**Comment by robertkowalski** [comment]
thank you for your question! you are right, this isn't documented yet

https://github.com/bitfinexcom/bitfinex-api-node/blob/9a43bb9fb52a46b58034b62bda5464f435fe10eb/ws2.js#L233-L244

are the methods to send and cancel orders via websocket.

there is now order event right now.

what you can do is to take a look at the message emitted from the `message` event and then filter for orders:

```js
bws.on('message', (msg) => { // ... })
```

hope that helps!

**Comment by brentkirkland** [comment]
Going to beef up these docs...
