### ISSUE TITLE
WS2: auth failed

### ISSUE THREAD

**Issue by glaucoheitor** [bitfinexcom/bitfinex-api-node#89]
Almost everytime I start my code i got this error:

`{ event: 'auth',
  status: 'FAILED',
  chanId: 0,
  code: 10100,
  msg: 'apikey: invalid' }`

this is part of my full code:

```var bws_API_KEY = '###'
var bws_API_SECRET = '###'
var bws = new BFX(bws_API_KEY, bws_API_SECRET, {version: 2,transform: true, autoOpen: false}).ws

bws.open();

bws.on('open', () => {
  bws.subscribeTicker('BTCUSD')
  bws.auth()
})

bws.on('auth', () => {
  console.log('authenticated')
})
```

i need to restart my code lots of time until i don't get this error message.

**Comment by robertkowalski** [comment]
hi, we just fixed an issue on the server side. can you double check if this is still an issue?

thank you!

**Comment by glaucoheitor** [comment]
it looks like it isn't anymore. thank you very much!
