### ISSUE TITLE
dependencies mistaked?

### ISSUE THREAD

**Issue by 2bbb** [bitfinexcom/bitfinex-api-node#9]
hi.
this is great module when use bitfinex.

but, maybe forgot `--save` option when `npm install debug`?
i use with `npm install debug` on project local.
i hope to resolve this problem, but i can't know really required version of debug module...

thanks.

**Comment by joshuarossi** [comment]
i will fix that

**Comment by joshuarossi** [comment]
should be taken care of...please let me know if you still have any trouble
