### ISSUE TITLE
Feedback over fork implementations

### ISSUE THREAD

**Issue by Tetradeca** [bitfinexcom/bitfinex-api-node#90]
Hey

I recently saw that this repository was a bit stale (but I guess was proved me wrong ;), and started doing some work on the library, you can find over at [this fork](https://github.com/HyperCubeProject/bitfinex-api-node/tree/lite).

To summarize what has been done:
- Removes the v1 clients: we don't really want to support them indefinitely and encourage people to switch to the newest API's. This would require a major release.
- Transform the rest client class into a simple factory and simplify internal logic
- Minor refactors of the ws client but still a class since it extends `EventEmitter`
- Integrates candles
- Integrates normalization process directly in the transformer
- Readme polishing

I understand that it's a good chunk of changes, so totally willing to discuss/adapt and send separate diffs.

**Comment by Tetradeca** [comment]
I've actually changed my mind regarding the suppression of the v1 clients, given the absence of a few methods on the v2 endpoint that I haven't noticed previously

**Comment by robertkowalski** [comment]
Thank you!

I'm taking a look this week!

**Comment by Tetradeca** [comment]
Sure! Just a note: the `lite` branch linked was the previous stuff I did, but there is still some interesting things. You should look at `master` now, where I basically created a rest client capable of querying both `v2` and `v1` APIs, which I think would be better while we wait for the stability of v2 and migration of previous methods.

I'm missing the different methods abstraction since I wasn't really sure what you would make of it.

**Comment by robertkowalski** [comment]
Cool, checking! And thanks for already sending PRs :)

**Comment by robertkowalski** [comment]
here is some feedback:

 - the test server helper is really cool. good work!
 - i'm impressed by your rest1/rest2 factory refactor. very clean and lean, much better than the big mess we had before. only thing to note: it seems some methods are missing? what are we going to do with methods that do just exist on the v1 or v2 endpoint?
 - i'm not sure about the transformer refactor. i think the current transformer implementation i wrote in spring is too monolithic. right now i think about a single, small transformer function *per method* instead of passing all data through one transformer. when i was implementing this, it turned out a bit hairy in the end as there were a lot more edge cases that came up in the end. with a transforming function per method we would avoid all the many different edge cases we have to keep track of right now.
 - the new way to handle events by removing the long if / else is quite nice, good idea.
 - README updates +1

**Comment by Tetradeca** [comment]
Ah thanks! 😃 

Yes I currently as you can see I only implemented the `candles` for the rest api while waiting, didn't want to do something that I don't use for nothing in case you would want to change it drastically. I can migrate the methods implemented in the two rest clients now. Maybe providing an api looking like:

```js
{
  makeAuthRequest,
  makePublicRequest,

  ticker,
  stats,

  v2: {
    candles,
  },
}
```

Effectively passing the v1 methods in the root, and the v2 ones still in beta in its own object, since we have a few name overlapping. After v2 is stable, we can reverse this, and pass a v1 object after doing a major release.

I agree that the transformer is very monolithic, and quite bug inducing. If a transformer-per-method approach is something you are already considering that's pretty good and I'm totally in favor.

**Comment by Tetradeca** [comment]
Bump 😄  @robertkowalski

**Comment by robertkowalski** [comment]
Thats a good idea!

Maybe we can even go further and put the v1 methods under `v1` to have a clear seperation.

From a users perspective methods like `makeAuthRequest ` would be available both in v1 and v2. This way a user can just do: require('../rest.js').v1 and everything needed is there.

What do you think?

**Comment by Tetradeca** [comment]
Yeah sounds good, not sure about the require returning directly the instances, since you still need to pass the secrets somewhere through the factory.

Duplicating the export of the `makeRequests` methods in both versions don't make much sense to me though, since It would be mostly used for unimplemented methods or testing.

```js
import { rest } from 'bitfinex-api-node'

const { v1, v2, makePublicRequest } = rest(key, secret)
```

 gonna try something out

**Comment by Tetradeca** [comment]
@robertkowalski  Alright I got something pretty nice [here](https://github.com/HyperCubeProject/bitfinex-api-node/commit/14c9a7e71fa11370ebf68cdf2375869e734d4eb9)!

Couple points:
- Use promises instead of callbacks
- I unified the behavior of the `parseInt` on orderIds, which was previously not done everywhere
- Created a transformer (and I get what you mean, it's tricky),  put it in the v2 file, only used on a couple methods.
- It's now pretty straightforward to copy params by using request querystring instead of copying the params using `for in`'s
- using dedicated `rest` folder, with index handling the base keys, options and make requests
- separate api methods into their own file to avoid conflicts `v1.js` and `v2.js`
- we only need to pass the two make request method to these two files, exposing a function and returning an object containing all the methods
- I haven't tried every single endpoint and didn't dare running the tests again ;)
- Probably will need some documentation

We might simplify the code even more by using spreads and destructuring, but I don't know your take on using something like babel in the future?

```js
const { rest } = BFX(key, secret)
                                                                                                
rest.v2.candles()                                                           
   .then(data => console.log(data))
```

**Comment by robertkowalski** [comment]
> your take on using something like babel in the future?

please no babel, let's stick with latest LTS to keep it simple.

**Comment by robertkowalski** [comment]
> Use promises instead of callbacks

i think that prepares async/await as well :) - have to sleep a night on the migration issue for current users and also get some feedback from @prdn et al in the team how we can handle that...

**Comment by Tetradeca** [comment]
Yep, I mean the quick'n easy solution would be to do a major bump of the lib too. Worth in my opinion, since as you said it opens the usage of `async`
