### ISSUE TITLE
How to pass parameters to payload?

### ISSUE THREAD

**Issue by alinberce** [bitfinexcom/bitfinex-api-node#94]
I am having problems accessing the API v1. Maybe I am starting on the wrong foot buy my goal is to fetch all orders done for a auth user. 

I thought of using `past_trades` which has a few parameters: symbol, timestamp, until, limit_trades, reverse. How do I actually pass the parameters? If I do something like:

bfx.past_trades('BTCUSD',{'timestamp': 1440191855}, function(error, response){
         //returns only a few trades, for this current month
})

The call I do, returns only a few trades and not since timestamp.

1. What am I doing wrong in passing the timestamp? How can I pass other parameters too, like reverse?
2. Is there a better way to obtain all done orders  history for the auth user?

**Comment by Tetradeca** [comment]
Yes you should be able to pass other flags like `reverse` or `until` like you did with the timestamp. You should maybe try tweaking `limit_trades` to return more? Also you should test to send the timestamp as a string, although I'm not sure it would matter.

**Comment by alinberce** [comment]
Indeed, you are right it works. Thank you for your info, playing with limit_trades returned more values.
Thank you.

I was wondering if all the V1 endpoints will be supported by V2? For instance on V2 I can't find past trades, only the active ones.

**Comment by Tetradeca** [comment]
That's what I think everyone would expect, but I believe they are pretty overwhelmed and don't have bandwidth to finish the beta api.

**Comment by robertkowalski** [comment]
The v2 api is still under *active* development. This week we deploy changes that improve the performance and add new endpoints, especially some missing from the V1 API: http://blog.bitfinex.com/api/api-improvements/

Take this with a grain of salt, but I think we try to provide the whole functionality from the V1 API as long as it isn't a major performance bottleneck.
