### ISSUE TITLE
API crashes without error message

### ISSUE THREAD

**Issue by lapwat** [bitfinexcom/bitfinex-api-node#98]
Hi everyone,
When I run my node server, it works find gathering tickers, order books and trades but then it crashes 5 minutes later without displaying any error. Shouldn't it be running forever if I don't kill it by hand ?
I am running v2.
Thanks for your advice

**Comment by Tetradeca** [comment]
Yep there shouldn't be any issue like this. Can you try doing:

```js
process.on('uncaughtException', (err) => {
  console.log(err)
})
```

**Comment by lapwat** [comment]
I just have to open the issue and the bug does not happen anymore :( I close the issue and will reopen it with detailed logs if the bug happens again.
