### ISSUE TITLE
Issue With Available Balance

### ISSUE THREAD

**Issue by jsonhuntrods** [bitfinexcom/bitfinex-api-node#99]
Hello,

This really doesn't have to do with an issue with this library, but more of an understanding of the Bitfinex API and what's happening on their end.

Right now I listen for wallet updates:
```
bws.on('wu', (msg) => {
*Place Order*
});
```

Once the wallet update comes in for a certain currency, I instantly try to sell it (using the balance in the wallet update). Every time I get "Invalid order: not enough exchange balance". Sometimes this happens because Bitfinex doesn't take the fees out of the amount given to me yet, but I get a second wallet update anytime the fees are taken out, so I can just relaunch the sell attempt again. But I still get the same error. I've even tried using the "use_all_available" parameter that is available on their API (not included in this package currently but I added it), it uses the right amount, but I still get the error.

Anyone else ever run into similar issues?

It's as if the wallet update event doesn't truly reflect when I have funds available to trade. Is there a different websocket event I should be listening for that is a better indicator?

**Comment by jsonhuntrods** [comment]
Same thing with the 'oc' event (which I assume means order complete), the only total there that is given is a total doesn't work...

**Comment by Tetradeca** [comment]
Hey, just a shot: did you make sure that the wallet update event you were receiving was from the `exchange` wallet? Some people get confused with the other two types, which would explain the insufficient funds error.

**Comment by lapwat** [comment]
Hi, try to sell a little less than your available balance. What is the result ?

**Comment by jsonhuntrods** [comment]
I think I got it. Here's the main takeaways:

1. The use_all_available parameter that is described in their documentation only works for buys.
2. When placing a sell on Bitfinex, even in the web interface, you have to account for the .1% and .2% fees. So I ended up using the 'tc' websocket event, and calculated my sells like this:

After Buy Completed: (1 - smaller_fee) * previous_amount_bought
After Sell Completed: (previous_amount_sold * sell_rate * (1 - bigger_fee)) - .00000001

previous_amount_bought, previous_amount_sold, and sell_rate values are passed in the tc event. This seems to work every time now. It seems weird that when you place a buy for let's say 1 arbitrary coin you don't actually have 1 coin (at least I think that's what is happening), most exchanges account for the fee in your trade cost instead of taking it after the trade completes.

Thanks a bunch! @lapwat @Tetradeca

**Comment by LRonHubs** [comment]
I still get this error, even after using the above suggestions

**Comment by runvnc** [comment]
The problem that I am having is that I am unable to find any reliable way to access timely updated balance data, using either the websocket or the REST API.  It seems as if this is in some non-consistent database that is updated as an afterthought, and often gives the correct result after a trade, but sometimes just hasn't been updated yet.  There is an option to ask for a recalculated balance.  I am doing that, but still not receiving correct balances in a timely manner.  This is also the case for the trade history as far as I can tell.  

I actually have the same problem with BItstamp.  I do not know if the problems with these exchanges' APIs is fraud, negligence, or just incompetence, but it certainly makes it difficult to trade consistently.
